### ISSUE TITLE
Problem with input files on square lattice in Standard mode

### ISSUE THREAD

**Issue by malga94** [issp-center-dev/HPhi#103]
Hi,

I am working on the frustrated antiferromagnetic Heisenberg model on a square lattice, with J, J3 > 0 where J is the nearest neighbour and J3 the third-nearest neighbour coupling. This is a model that (without anisotropies) I think can easily be solved with HPhi in standard mode. From the manual (section 4.1.4) I understand that the couplings I am looking for should be the simplified parameters J and J’' on a tetragonal lattice (I attach the Standard.txt file for clarity).

But when I run standard mode, the generated input files are not how I expect: in exchange.def, there seems to be a J3 coupling missing for each site, and a different value for the nearest neighbour coupling in the x and y directions. I attach two input files, HPhi_exchange.txt which contains the input file produced by HPhi in standard mode, and my_exchange.txt where I have written the exchange input file that I would expect for this model.
[Standard.txt](https://github.com/issp-center-dev/HPhi/files/5081326/Standard.txt)
[my_exchange.txt](https://github.com/issp-center-dev/HPhi/files/5081327/my_exchange.txt)
[HPhi_exchange.txt](https://github.com/issp-center-dev/HPhi/files/5081328/HPhi_exchange.txt)

I think it is most likely that I am misunderstanding the manual: in that case, could you please inform me on the correct parameters to use in Standard.in to simulate the isotropic Heisenberg model with J>0 and J3>0 on the square lattice with periodic boundary conditions?

Thank you in advance,
Kind regards

**Comment by mitsuaki1987** [comment]
Dear @malga94 
Thank you for reporting.
There is a bug in the standard mode for the square lattice with the third nearest-neighbor interaction.
 https://github.com/issp-center-dev/StdFace/blob/1f9e0dbe66a6bb0df5d9f5c5b5bc70492f54a26d/src/SquareLattice.c#L263-#L267
This "1" should be "2".
This bug will be fixed in the next release.

Best regards,
Mitsuaki Kawamura(ISSP)

**Comment by tmisawa** [comment]
Hi, 

Thank you very much for pointing out a problem with J3.
I examined the code of Standard mode and found that
there is a bug in the definition of J3.
Please see the following PR:

https://github.com/issp-center-dev/StdFace/pull/3/commits/eeabebaec5e88eafc2c94c7c65f91ed03418f728

I confirm that the bug-fixed version reproduces your exchange input file.
Based on the PR,
we will update and release the bug-fixed version soon.

Thank you again for pointing out the bug.

Best,
Takahiro Misawa

**Comment by malga94** [comment]
No problem, thank you for the quick reply!
I will now close the issue.

Kind regards,
Filippo
