### ISSUE TITLE
Problem in Installation of  HPhi-3.4.0.tar.gz

### ISSUE THREAD

**Issue by sachin00-github** [issp-center-dev/HPhi#106]
Following command for installation of `HPhi-3.4.0`  lands in some errors.

`$ cmake ../HPhi-3.4.0/`

###### Here, I am attaching the relevant part of  log of `cmake`

------------------------------------------------------------------------------------------------------------
**sachin@sachin:~/Downloads/HPhi.build$cmake ../HPhi-3.4.0/**
.........................
A library with LAPACK API found.
-- Configuring done
CMake Error at src/CMakeLists.txt:41 (add_executable):
  Cannot find source file:

    /home/sachin/Downloads/HPhi-3.4.0/src/StdFace/clone/src/ChainLattice.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at src/CMakeLists.txt:41 (add_executable):
  No SOURCES given to target: HPhi

CMake Generate step failed.  Build files cannot be regenerated correctly.
-----------------------------------------------------------------------------------------------------------

I will appreciate your help.

**Comment by k-yoshimi** [comment]
Sorry for my late reply.
From ver. 3.4.0, StdFace is introduce as the submodule. 
So, source codes of StdFace is installed over the internet using git.
Please check that git is installed in your system.

**Comment by sachin00-github** [comment]
Oh!, I have installed HPhi-3.3.1 for the time being.
Ok, I will follow your suggestion, will get back to you. 

And, Thanks for your reply. 

Sachin
