### ISSUE TITLE
Keep Sz non-fixed in Canonical Hubbard

### ISSUE THREAD

**Issue by sankrad** [issp-center-dev/HPhi#109]
Dear Developers,

Thank you very much for your great code!

Could you please help me with an issue? The manual reads that in the canonincal regime (expert mode) I migth chose not to specify total Sz. However when I am trying to do so, just skipping the line in modpara.def, I am getting an error.

My modpara.def:

```
--------------------
Model_Parameters
--------------------
Canonical Hubbard
--------------------
CDataFileHead   lgm
--------------------
--------------------
Nsite   4
Ncond 4
Lanczos_max   999
initial_iv -2
exct   1
LanczosEps   12
LanczosTarget   2
```

The error: 
```
"Error: in sz.
imax = 2, Check.idim_max=1"
```

Kind regards,
Anton.

**Comment by k-yoshimi** [comment]
@sankrad 
I'd like to check your input files.
After compressing all the input files into a zip file, could you upload it here ?

**Comment by sankrad** [comment]
Dear k-yoshimi,

Thank you for the fast response!

[hphi_configs.tar.gz](https://github.com/issp-center-dev/HPhi/files/5848667/hphi_configs.tar.gz)

**Comment by k-yoshimi** [comment]
@sankrad 
Did you use 16 processes for your calculation ?

**Comment by sankrad** [comment]
Yes, exactly...

**Comment by k-yoshimi** [comment]
Please use 1 process or 4 processes for this calculation, since this system is too small for 16 processes parallelization.

In the following, the process element info (written in standard output) for16 processes parallelization is shown. 
```
INTRA process site
    Site    Bit
       0       4
       1       4

  INTER process site
    Site    Bit
       2       4
       3       4

  Process element info
    Process       Dimension   Nup  Ndown  Nelec  Total2Sz   State
          0               1     0      0      4         0   0000
          1               4     0      0      3         0   0100
          2               4     0      0      3         0   1000
          3               6     0      0      2         0   1100
          4               4     0      0      3         0   0001
          5               6     0      0      2         0   0101
          6               6     0      0      2         0   1001
          7               4     0      0      1         0   1101
          8               4     0      0      3         0   0010
          9               6     0      0      2         0   0110
         10               6     0      0      2         0   1010
         11               4     0      0      1         0   1110
         12               6     0      0      2         0   0011
         13               4     0      0      1         0   0111
         14               4     0      0      1         0   1011
         15               1     0      0      0         0   1111
```
You can see 0 electron state at 15 process. 
In HPhi, the process number is used to represent the electron states.
At 15 process, 4 electrons are assigned(15=3*4^1+3*4^0, here 3*4^n means doubloon state at n-th site).
So the inner process cannot have any electron and HPhi fails the calculation.

**Comment by sankrad** [comment]
Oh, that was a stupid one! Thank you for the very fast assistance.
