### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by magnon00** [issp-center-dev/HPhi#118]
**Received some errors while installing `3.4.1`:**

       cmake ../HPhi-3.4.1/
       -- Build type: Release
       -- The C compiler identification is GNU 10.3.0
        -- The Fortran compiler identification is GNU 10.3.0
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: /usr/bin/cc - skipped
        -- Detecting C compile features
      -- Detecting C compile features - done
       -- Detecting Fortran compiler ABI info
       -- Detecting Fortran compiler ABI info - done
       -- Check for working Fortran compiler: /usr/bin/gfortran - skipped
      -- Checking whether /usr/bin/gfortran supports Fortran 90
      -- Checking whether /usr/bin/gfortran supports Fortran 90 - yes
      -- git clone https://github.com/issp-center-dev/StdFace 
      Cloning into 'clone'...
      -- git checkout master
      Already on 'master'
     Your branch is up to date with 'origin/master'.
      -- Found OpenMP_C: -fopenmp (found version "4.5") 
     -- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
       -- Found OpenMP: TRUE (found version "4.5")  
      -- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS)
     -- Could NOT find MPI_Fortran (missing: MPI_Fortran_LIB_NAMES MPI_Fortran_F77_HEADER_DIR           MPI_Fortran_MODULE_DIR MPI_Fortran_WORKS) 
     -- Could NOT find MPI (missing: MPI_C_FOUND MPI_Fortran_FOUND)** 
         Reason given by package: MPI component 'CXX' was requested, but language CXX is not enabled.  

       -- Looking for Fortran sgemm
       -- Looking for Fortran sgemm - not found
        -- Looking for pthread.h
       -- Looking for pthread.h - found
        -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
          -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
        -- Found Threads: TRUE  
        -- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
       -- LAPACK requires BLAS
       --A library with LAPACK API not found. Please specify library location.
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /home/sachin/HPhi.build

Kindly Help

**Comment by tmisawa** [comment]
@sachin00-github 
Hi. Thie error seems to be induced by the missing of BLAS.
