### ISSUE TITLE
HPhiの古いwebsiteが更新されていない

### ISSUE THREAD

**Issue by ultimatile** [issp-center-dev/HPhi#121]
「HPhi」でGoogle検索するとトップに出てくるwebsiteが
http://issp-center-dev.github.io/HPhi/index.html
で, HPhiの開発が2年間止まってるのかと思っていました.
古いwebsiteから新しいwebsiteに誘導するなどした方が良いのではないでしょうか.

**Comment by wistaria** [comment]
redirection完了してますね？閉じてよいでしょうか？

**Comment by ultimatile** [comment]
そうですね
ご対応いただきありがとうございました
