### ISSUE TITLE
`HPhi/samples/tutorial_1.6/MakeDef.py` seems do not read `input.txt`

### ISSUE THREAD

**Issue by HengyueLi** [issp-center-dev/HPhi#129]
As following [tutorial](https://issp-center-dev.github.io/HPhi/manual/develop/tutorial/en/html/zero_temperature/expert.html), `run.sh` seems report error. By a glance a `MakeDef.py`, I guess `Ns` is not read. Can you check that? Or there is something wrong with my understanding?

**Comment by tmisawa** [comment]
Hi @HengyueLi .

Thank you for pointing out a problem in MakeDef.py.

As you pointed out, the number of sites is fixed to 2.
I fixed this bug in the branch "debug_tutorial".
Please check it.

https://github.com/issp-center-dev/HPhi/commit/8b6521dc230acd4c83bfb44b93ca1822bf68155e

**Comment by HengyueLi** [comment]
Great, the problem is solved.
