### ISSUE TITLE
Problem with non-diagonal interaction in 2-spin mode

### ISSUE THREAD

**Issue by HengyueLi** [issp-center-dev/HPhi#130]
Consider a two-spin system. The Hamiltonian is defined as `H= S_x S_z`. With a local rotation at the first spin, this system should equivalent to `H= S_z S_z`. So the energy should be +/- 0.25.  But I get 0. 
To produce the problem, just set `0 1 x z 1` in the `pair.txt`. In case of any other influence, I upload the configuration ('test.zip'). One can run `run.sh` directly. Please notice the last line in `run.sh`. I redefined `hphi` as the bin file of HPhi. 
[test.zip](https://github.com/issp-center-dev/HPhi/files/8536746/test.zip)

**Comment by tmisawa** [comment]
@HengyueLi 

I am sorry that there is a bug in the site index in MakeDef.py 
I also fixed a bug. please check it.

https://github.com/issp-center-dev/HPhi/commit/9a8fb13e85b344fc924d93df11149f0a66c4a84a

**Comment by tmisawa** [comment]
And, please note that for off-diagonal interactions, this script add

**Comment by HengyueLi** [comment]
Thanks for the explanation. And also, the script is working now.
