### ISSUE TITLE
tutorial_1.6 fails for hphi 3.5.1

### ISSUE THREAD

**Issue by wistaria** [issp-center-dev/HPhi#136]
```
  Read File 'locspn.def'.
  Read File 'Exchange.def'.
  Read File 'InterAll.def'.
Error: NonHermite (i, spni, j, spnj, k, spnk, l, spnl) = (0, 0, 0, 1, 1, 0, 1, 1), InterAll_re= 0.000000, InterAll_im= -0.600000 . 
Error: NonHermite (i, spni, j, spnj, k, spnk, l, spnl) = (0, 1, 0, 0, 1, 1, 1, 0), InterAll_re= 0.000000, InterAll_im= 0.600000 . 
Error: NonHermite Pair exists in InterAll. 
Error: Indices and Parameters of Definition files(*.def) are incomplete.
```

**Comment by wistaria** [comment]
tutorial_1.6 passed for hphi 3.5.0

**Comment by jringler6** [comment]
Has this question for hphi 3.5.1 been addressed in a different conversation? I'm trying to learn the program now and 3.5.1 is still throwing me the same error as the original post listed above.

**Comment by tmisawa** [comment]
@jringler6 
Hi. I updated `MakeDef.py` so as to generate proper `InterAll.def`, 
which satisfies the new policy for detecting Hermitian conjugates.
For details, please see PR #137 .
