### ISSUE TITLE
Problem in running tutorial_4.3

### ISSUE THREAD

**Issue by hcut** [issp-center-dev/HPhi#151]
Hi
I am getting the following trivial error while running the `tutorials4.3` which is the  program for calculating dynamical spin structure factors.

            (base) run@run:~/HPhi-3.5.1/samples/tutorial_4.3$ ./run.sh 
            Error
            Usage: python do_all.py path_to_HPhi.
            path_to_HPhi: relative or absolute path to HPhi.

Could you please help me in sorting this error. I will thankful to you.

**Comment by tmisawa** [comment]
Please specify the path to HPhi executable as an argument in `run.sh`.
For example, `sh ./run.sh /usr/bin/HPhi`.
This means that HPhi executable is located in `usr/bin` .

**Comment by quantum-magnet** [comment]
ok, thanks, worked!
