### ISSUE TITLE
How should I use the utility greenr2k provided by HPhi?

### ISSUE THREAD

**Issue by willOcean1** [issp-center-dev/HPhi#168]
1.Before using greenr2k, it seems that I still need to input some content into geometry.dat? Is it the high symmetry point of the model?
2.Can the two body Green's function required for greenr2k be arbitrarily defined? What rules do we still need to meet.
Because I want to apply it to the kitaev model, but does the correlation function of the kitaev model have strong key correlation? Do I need any special attention
Thank you!

**Comment by mitsuaki1987** [comment]
Dear [willOcean1](https://github.com/willOcean1)

1,
> I still need to input some content into geometry.dat? Is it the high symmetry point of the model?

You are right.
For the file format of geometry.dat,
https://issp-center-dev.github.io/HPhi/manual/master/en/html/fourier/format.html
the standard-mode fills contents (1)-(4), and you need to fill (5)-(7) by yourself.

2,
The required two-body site-spin indices for the correlation function are listed here:
https://issp-center-dev.github.io/HPhi/manual/master/en/html/fourier/format.html#one-and-two-body-correlation-function-in-the-site-representation
They are automatically generated by the standard mode.
