### ISSUE TITLE
固有ベクトルの出力について

### ISSUE THREAD

**Issue by tmisawa** [issp-center-dev/HPhi#17]
マニュアルで固有ベクトルの出力形式が、
一行目のint01の形式がint型を
なっていますが、long int 型の間違いでしょうか？

また、また int02 と double01
の間に128bitの余計なものが入っていますが、
これはなんでしょうか？

ご回答をよろしくお願いいたします。

**Comment by k-yoshimi** [comment]
@tmisawa 
>マニュアルで固有ベクトルの出力形式が、
一行目のint01の形式がint型を
なっていますが、long int 型の間違いでしょうか？

はい、間違いです。

> また、また int02 と double01
の間に128bitの余計なものが入っていますが、
これはなんでしょうか？

計算の仕様で、固有ベクトルの最初に計算に使用しない成分をいれています。
出力では便宜上その成分も吐き出しています。
本点については、マニュアルに記載しておりませんでしたので、
次回のバージョンアップの際に変更しておくようにいたします。

**Comment by ultimatile** [comment]
MPI並列時の出力時について質問なのですが,
・MPI並列した場合,それぞれのrankの固有ベクトル出力の最初に計算していない成分があるという認識で正しいですか？
・MPI並列で分かれた固有ベクトルから元の(MPI並列していない)固有ベクトルを作る場合,rank0から昇順に結合すればよろしいでしょうか？

**Comment by mitsuaki1987** [comment]
@ultimatile 
その通りです。

**Comment by ultimatile** [comment]
お早いご回答ありがとうございます.

**Comment by k-yoshimi** [comment]
@ultimatile
捕捉説明いたします。HΦではプロセス並列する際に、自身のランクをビットとみなして計算しています。その際、出力されるものは内部のビットのみを吐き出しています。そのため、1プロセスに統合する場合には、もとのヒルベルトスペースに拡張した際、各ランクが持つべき値を足し合わせる必要があります。

たとえば、4サイトスピン模型で、プロセス数2^1とした場合は、4サイト目が各ランクのビットで表現されます。そのため、ランク0のもの0×2^3、ランク1のものは1×2^3だけたしあげる必要があります。昇順に結合される場合には、その点、ご注意ください。

**Comment by ultimatile** [comment]
補足説明ありがとうございます.
