### ISSUE TITLE
LanczosTarget has no effect?

### ISSUE THREAD

**Issue by Shovan-Physics** [issp-center-dev/HPhi#176]
Hi, I am trying to use HPhi-3.5.2 to find low-energy eigenstates of some spin models. For `#CalcType = 0:Lanczos` and `#CalcModel = 1:Spin`, I find that the parameter `LanczosTarget` does not have any effect. When I set `exct = 2` and `LanczosTarget  = 2` to find the first excited state, the log file shows that the target energy is `E[3]`, i.e., the second excited state. In general, the target seems to be always `exct + 1` (see below for a screenshot).

Probably for this reason the `CG` method (which takes more RAM) is always faster than `Lanczos` for the same parameters. Is there a way around this?

Also, the `Lanczos` method seems to automatically calculate the ground-state energy as well, when `exct = 2`. But the output only gives data for the first excited state. Can it also export the ground state like `CG`?

Many thanks,
Shovan

Below is how my `modpara` file looks like:
<img width="145" alt="modpara" src="https://github.com/user-attachments/assets/0268b124-5355-4049-866b-07b774519d05">

But the log file shows the target is different from `LanczosTarget`:
<img width="622" alt="logfile" src="https://github.com/user-attachments/assets/522e1963-ea46-4735-b29a-6e7e65ce5a9a">

**Comment by ultimatile** [comment]
- The target is `E[Lanczos_Target + 1]`. Therefore, it appears to be correct.
- Lanczos method for targeting excited states is generally less reliable compared to CG or full diagonalization methods. The output eigenvalue in `zvo_energy.dat` should correspond to the excited state. Please confirm the value of the target eigenvalue at the last `stp` line, as it may converge to an incorrect value (potentially, the target eigenvalue being overridden by the CG method run after the Lanczos iteration). The illusional convergence to the ground state (or an incorrectly lower excited state) is the infamous spurious eigenvalue problem of the Lanczos method. Please use the `CG` method to achieve correct results. It's necessary to ensure the correctness.

**Comment by ultimatile** [comment]
This might be a pretty sick example.

## Standard input file
```
model="spin"
method="Lanczos"
lattice="chain"
L=8
2S=2
J=1
2Sz=0
exct=2
LanczosTarget=4
```

## Some of standard output
```
LanczosStep  E[1] E[2] E[3] E[4] Target:E[5] E_Max/Nsite
... omitted ...
  stp = 59 -11.3369560779 -10.7434008235 -9.5965599465 -9.3435961395 -9.2184540761 1.0000000000
  stp = 60 -11.3369560779 -10.7434008235 -9.5965599465 -9.3435961395 -9.2184540761 1.0000000000
  stp = 61 -11.3369560779 -10.7434008235 -9.5965599465 -9.3435961395 -9.2184540761 1.0000000000
  stp = 62 -11.3369560779 -10.7434008235 -9.5965599465 -9.3435961395 -9.2184540761 1.0000000000
  stp = 63 -11.3369560779 -10.7434008235 -10.3131540771 -9.5965599465 -9.3435961395 1.0000000000
  stp = 64 -11.3369560779 -11.0772177055 -10.7434008235 -9.5965599465 -9.3435961395 1.0000000000
  Lanczos EigenValue in vec12 = -11.3369560779

######  End  : Calculate Lanczos EigenValue.  ######

######  Start: Calculate Lanczos Eigenvec.  ######

  Start: Calculate Lanczos Eigenvector.
  End  : Calculate Lanczos Eigenvector.
  Start: Calculate Energy.
  End  : Calculate Energy.

  Accuracy check !!!
  LanczosEnergy = -1.10772177054964e+01
  EnergyByVec   = -1.10772177054964e+01
  diff_ene      = 3.20722565291614e-16
  var           = 1.26216636370843e-02
  Accuracy of Lanczos vectors is NOT enough

  Start: Calculate EigenVector by CG method.
  End  : Calculate EigenVector by CG method.
  Start: Calculate Energy.
  End  : Calculate Energy.

  CG Accuracy check !!!
  LanczosEnergy = -1.10772177054964e+01
  EnergyByVec   = -1.13369560760445e+01
  diff_ene      = 2.34479792176676e-02
  var           = 8.55747585338413e-12
```

After the Lanczos iteration, the target eigenvalue obtained is `E[2] = LanczosEnergy = -11.0772177055`, whereas the correct eigenvalue should be `-10.7434008235`, as obtained by the Full Diagonalization method and observed before the last `stp` line. The value `-11.0772177055` does not belong to the spectrum, resulting in a large energy variance of `var = 1.26216636370843e-02`. Subsequently, after the CG iteration following the Lanczos iteration, the incorrect value`-11.0772177055` is lower than the actual `E[2] = -10.7434008235`, causing the state to erroneously converge to the ground state `E[1] = -11.3369560779`. (This results in a significant energy difference between the Lanczos and Lanczos+CG methods `diff_ene = 2.34479792176676e-02`.) Consequently, `E[2] = EnergyByVec = -11.3369560779` is written in `zvo_energy.dat`.

Probably, in most "less sick" cases, `Accuracy of Lanczos vectors is enough`, and therefore, the CG method after the Lanczos iteration is not called. In such cases, the target energy at the final `stp` line (`LanczosEnergy`) would be written directly to `zvo_energy.dat`.

**Comment by Shovan-Physics** [comment]
Thanks for your detailed and quick reply. I understand the problem with Lanczos for excited states. However, let us suppose that I am only interested in the ground state. In this case, I would expect that we should target `E[1]`. However, even if I give `LanczosTarget = 0` it shows that the target is `E[2]`, i.e., we check for convergence in `E[2]`. Why is that?

### Input
```
model="spin"
method="Lanczos"
lattice="chain"
L=8
2S=2
J=1
2Sz=0
exct=1
LanczosTarget=0
LanczosEps=8
```
### Output 
```
initial_mode=1 (random): iv = -1 i_max=1107 k_exct =1 

LanczosStep  E[1] E[2] E[3] E[4] Target:E[2] E_Max/Nsite
stp = 2 -4.3781625619 2.2864952000 xxxxxxxxxx xxxxxxxxx  2.2864952000 xxxxxxxxx 
stp = 3 -6.4531929040 -0.9904345528 4.0800891521 0.0000000000 -0.9904345528 0.5100111440
stp = 4 -7.7016030273 -3.3501473845 1.1535195427 5.2014819718 -3.3501473845 0.6501852465
stp = 5 -8.9357573864 -5.4770931948 -1.2915510609 2.6730522450 -5.4770931948 0.7538520279

... omitted ...

stp = 27 -11.3369560774 -10.7434000982 -9.5897001369 -9.2694257350 -10.7434000982 0.9999999843
stp = 28 -11.3369560778 -10.7434005451 -9.5914626316 -9.2745974833 -10.7434005451 0.9999999947
stp = 29 -11.3369560779 -10.7434007196 -9.5927807838 -9.2795077867 -10.7434007196 0.9999999984
stp = 30 -11.3369560779 -10.7434007883 -9.5939371208 -9.2857884480 -10.7434007883 0.9999999995
Lanczos EigenValue in vec12 = -11.3369560779

... omitted ...

Accuracy of Lanczos vectors is enough.
```

Clearly, `E[1]` has converged to a relative error of `10^-LanczosEps` well before `stp = 30`, and the algorithm is checking for convergence in `E[2]`.

**Comment by ultimatile** [comment]
If `LanczosTarget`<`exct`, then it will become `LanczosTarget`=`exct` (Target will be `E[2]`). It's the current implementation. I have no idea why the target should be `E[1]` for the GS energy calculation.

https://github.com/issp-center-dev/StdFace/blob/bfc57fb9ddf515e11e6f9730201b0dce37c77db3/src/StdFace_main.c#L1899

**Comment by Shovan-Physics** [comment]
OK, thanks for the clarification. I understand how it works now. 

`E[1]` gives the ground-state energy, so I thought that should be the default target for a ground-state calculation, but maybe I'm missing something. In fact, the user guide (pages 39 & 52) also says:

```
LanczosTarget
The target eigenenergy... If it is set to 1, the target eigenenergy becomes the ground state.
```

**Comment by ultimatile** [comment]
If I remember correctly, targeting `E[1]` may have been possible in versions before 2.0.0. The documentation might not have been updated since the change.

**Comment by Shovan-Physics** [comment]
I see, thanks.
