### ISSUE TITLE
How to prove a two-dimensional antiferromagnetic material?

### ISSUE THREAD

**Issue by sidy1073662254** [issp-center-dev/HPhi#177]
Hi, dear developers

Recently, I used HPhi to calculate the ground state energy of a two-dimensional Heisenberg model. I did not constrain the total of **Sz** in grand canonical ensemble. For example:
`W = 2
L = 3
model = "SpinGC"
method = "CG"
lattice = "Honeycomb"
J0x = -1.0
J0y =  0.0
J0z =  0.0
J1x =  0.0
J1y = -1.0
J1z =  0.0
J2x =  0.0
J2y =  0.0
J2z = -1.0
2S=1
exct = 10`

And I found the first four energies are degenerate.
![截图20240804225643](https://github.com/user-attachments/assets/d827b9f0-da9d-4e44-bed2-0623baac87bc)

Due to **Sz** of the ground state is zero, I thought it had an antiferromagnetic configuration in **z**-axis. In order to verify this idea, I calculated the average of **Sz** and spin susceptibility with **TPQ** method. For example:
`W = 2
L = 3
model = "SpinGC"
method = "TPQ"
lattice = "Honeycomb"
J0x = -1.0
J0y =  0.0
J0z =  0.0
J1x =  0.0
J1y = -1.0
J1z =  0.0
J2x =  0.0
J2y =  0.0
J2z = -1.0
2S=1
`
With the Flct_rand.dat, I calculated the average of **Sz** and spin susceptibility with temperature.
`(*Using Mathematica*)
DataAll=Import["C:\\Users\\10736\\Desktop\\Flct_rand2.dat"][[4;;]];
tem=1/DataAll[[;;,1]];
MeanOfSz=DataAll[[;;,6]];
MeanOfSzSquare=DataAll[[;;,7]];
SpinSusceptibility=(#3-#2^2)/#1&@@@Thread[{tem,MeanOfSz,MeanOfSzSquare}];
ListLogLinearPlot[Thread[{tem,MeanOfSzSquare}],Joined->True,Frame->True,FrameLabel->{"T","m_z"},FrameTicks->True,FrameStyle->Black,PlotTheme->"LargeLabels",PlotRange->All]
ListLogLogPlot[Thread[{tem,SpinSusceptibility}],Joined->True,Frame->True,FrameLabel->{"T","spin susceptibility"},FrameTicks->True,FrameStyle->Black,PlotTheme->"LargeLabels",PlotRange->All]`

The results are shown below:
![截图20240804231014](https://github.com/user-attachments/assets/2345d95b-5893-4f3f-80ea-bd7e017b5560)
I found that **m_z** is not equal to zero at low temperatures, and spin susceptibility monotonically decreases with temperature. This result seems to indicate that it is a ferromagnetic material at low temperature. How should I comprehend two results?

Regards,
Y.D.Shen.

**Comment by ultimatile** [comment]
I've tried the TPQ calculation with the input file you've provided as shown below:

```
W = 2
L = 3
model = "SpinGC"
method = "TPQ"
lattice = "Honeycomb"
J0x = -1.0
J0y =  0.0
J0z =  0.0
J1x =  0.0
J1y = -1.0
J1z =  0.0
J2x =  0.0
J2y =  0.0
J2z = -1.0
2S=1
```

As a quick check, I've plotted $T$ vs $S_z$ written in `Flct_rand*.dat`

![Fig](https://github.com/user-attachments/assets/6aac3286-c9cb-4f32-b09b-ab95c8ea3317)

zoomed figure of the area around $S_z=0$ at low temperatures.

![Fig_zoom](https://github.com/user-attachments/assets/a0416d24-84ca-488b-a809-d4e36b459e01)

It appears that  $S_z$  will fall to zero as the temperature decreases, which is consistent with your expectation. 
Averaging over these samples would not change the observation.
I'm not sure why you've started the finite temperature calculation. If you would like to reveal the ground state property with  $S_z = 0$, performing the ground state calculation of antiferromagnetic order parameters is more conventional.

**Comment by sidy1073662254** [comment]
Thank you very much for your help. The problem has now been solved.
