### ISSUE TITLE
compiler error while dynamical linking 

### ISSUE THREAD

**Issue by fyangtcmp** [issp-center-dev/HPhi#178]
While linking to the Fortran shared library libkomega.so and the executable cTPQ, greenr2k, the error occured
`ifort: command line remark #10148: option '-i_dynamic' not supported`
My compiler is intel parallel studio 2019 and I guess this option should be replace by '-shared-intel'.  What should I do to change this compiler options in Cmake?

**Comment by fyangtcmp** [comment]
I use the 3.5.2 version of Hphi. My operating system is Red Hat 4.8.5. And I attached the CMakeCache.txt file
[CMakeCache.txt](https://github.com/user-attachments/files/16494495/CMakeCache.txt)

**Comment by fyangtcmp** [comment]
I have solved this issue. The version of cmake I have used is too old... cmake/3.14.3 can handle the options correctly.

**Comment by yomichi** [comment]
I'm glad to hear the problem is solved.
We will bump up the minimum supported version of cmake specified in CMakeLists.txt.
Thank you for reporting the issue.
