### ISSUE TITLE
ladderの相互作用がmanualと逆になっている

### ISSUE THREAD

**Issue by ultimatile** [issp-center-dev/HPhi#179]
マニュアルの`lattice="ladder"`の図で $J_2$ と $J_2'$ が実際と逆になっていると思います．

<img width="607" alt="Fig4 4" src="https://github.com/user-attachments/assets/1ee75f54-38d8-4792-862f-d7d12971b6e8">

https://github.com/issp-center-dev/HPhi/blob/master/doc/figs/ladder.png

`lattice.gp`の出力
<img width="400" alt="lattice" src="https://github.com/user-attachments/assets/e7f24105-e90d-4b20-9289-8f56ade63c3f">

## $J_2=1$

`J2=1`のときの`stan.in`

```
model="spin"
lattice="ladder"
method="Lanczos"
L = 8
W = 3
2S=1
2Sz=0
J2=1
```

`J2=1`のときの`exchange.def`の出力

```
=============================================
NExchange         16
=============================================
====== ExchangeCoupling coupling ============
=============================================
    0     4         0.500000000000000
    1     5         0.500000000000000
    3     7         0.500000000000000
    4     8         0.500000000000000
    6    10         0.500000000000000
    7    11         0.500000000000000
    9    13         0.500000000000000
   10    14         0.500000000000000
   12    16         0.500000000000000
   13    17         0.500000000000000
   15    19         0.500000000000000
   16    20         0.500000000000000
   18    22         0.500000000000000
   19    23         0.500000000000000
   21     1         0.500000000000000
   22     2         0.500000000000000
```

## $J_2'=1$

`J2=1`のときの`stan.in`

```
model="spin"
lattice="ladder"
method="Lanczos"
L = 8
W = 3
2S=1
2Sz=0
J2'=1
```

`J2'=1`のときの`exchange.def`の出力

```
=============================================
NExchange         16
=============================================
====== ExchangeCoupling coupling ============
=============================================
    0    22         0.500000000000000
    1    23         0.500000000000000
    3     1         0.500000000000000
    4     2         0.500000000000000
    6     4         0.500000000000000
    7     5         0.500000000000000
    9     7         0.500000000000000
   10     8         0.500000000000000
   12    10         0.500000000000000
   13    11         0.500000000000000
   15    13         0.500000000000000
   16    14         0.500000000000000
   18    16         0.500000000000000
   19    17         0.500000000000000
   21    19         0.500000000000000
   22    20         0.500000000000000
```

また， $J_1$ の下の方の矢印が一点破線になっているので直していただけないでしょうか？

**Comment by k-yoshimi** [comment]
@ultimatile 
コメントありがとうございます。
(番号付がlattice.gpとx方向で逆になっているのも気になるので、そちらも確認しておくようにします。)

**Comment by mitsuaki1987** [comment]
報告どうもありがとうございます。
@k-yoshimi これはマニュアルの図の方を直しておくという対応で良いですか？

**Comment by k-yoshimi** [comment]
@mitsuaki1987 
はい、それで大丈夫だと思います。
lattice.gpの出力で、右から左に番号が振られていくのが少し気味が悪いのですが、マニュアルのように左から右に振るように修正することはできますか？

**Comment by mitsuaki1987** [comment]
lattice.gpに関しては正確に言うとこのように縦向きになっていて、
![temp](https://github.com/user-attachments/assets/f7f645cd-9cec-41d7-bd44-393d1d460ce6)
Wが芯の本数、Lが段数を表しています。マニュアルはそれを90度回転させたもの、にしようとしていろいろと間違えているようです。
という事で、マニュアルの方も縦向きにしておきますか？

**Comment by mitsuaki1987** [comment]
@k-yoshimi @ultimatile これでどうでしょう
![ladder](https://github.com/user-attachments/assets/463fe892-a895-4ab4-89fc-7c66a43e689d)

**Comment by ultimatile** [comment]
修正ありがとうございます．あとは梯子と凡例の $J_1$ の矢印の線種が統一されれば問題ないと思います（この向きの梯子格子の図はあまり覚えがないですが）．これは梯子の方にある矢印が一点破線になるのが当初の意図通りでしょうか？

**Comment by mitsuaki1987** [comment]
https://raw.githubusercontent.com/issp-center-dev/HPhi/51f3b87e4f4d24c6ebeaaf9261714effb2367548/doc/figs/ladder.png
線種忘れていました。直しました。

**Comment by k-yoshimi** [comment]
あまり見かけないladderになってますが、整合性が取れていれば大丈夫だと思います。
修正ありがとうございます。

**Comment by ultimatile** [comment]
問題ないと思います．
ありがとうございました．
