### ISSUE TITLE
Hello, can I use open boundary conditions in the standard mode? If so, how should I set it up?

### ISSUE THREAD

**Issue by willOcean1** [issp-center-dev/HPhi#182]

**Comment by ultimatile** [comment]
The standard mode does not support the open boundary condition.
The easiest way is to remove the boundary terms by hand in the Hamiltonian's input files for expert mode.

## Example: spin chain

Let the name of the input file `stan.in` for standard mode as shown below.

```
model="spin"
method="Lanczos"
lattice="chain"
L=4
2S=1
J=1
2Sz=0
```

You can generate the input file for expert mode by HPhi's dry mode: `HPhi -sdry stan.in`
After performing the command, you can find many input files with the extension `.def`.

As an example, `exchange.def`, which is for spin exchange interactions is

```
=============================================
NExchange          4
=============================================
====== ExchangeCoupling coupling ============
=============================================
    0     1         0.500000000000000
    0     3         0.500000000000000
    1     2         0.500000000000000
    2     3         0.500000000000000
```

By removing the line ` 0     3         0.500000000000000`, you can make the Hamiltonian with the open boundary condition.
The pain of doing this depends on the lattice geometry and the number of kind of Hamiltonian terms, for example, 2d lattices are more cumbersome.
