### ISSUE TITLE
対角化のリスタートについて

### ISSUE THREAD

**Issue by ultimatile** [issp-center-dev/HPhi#23]
```
CalcType   0
CalcModel   1
ReStart   2
CalcSpec   0
CalcEigenVec   0
InitialVecType   1
InputEigenVec   0
OutputEigenVec   1
```
のような`CalcMod.def`(一回目はRestart 1)で計算を行っています.
`Restart 1`のときは6時間走ったのですが,`Restart 2`にすると計算が6分程度で止まってしまいます.
これは仕様でしょうか.
また計算を中断するタイミングを設定することは出来ないのでしょうか.

また上記設定で出力されるリスタートに用いる固有ベクトルの名前が`zvo_recalcvec_rank_0.dat`になっているのですが,何か設定を間違えているのでしょうか.(`zvo_TimeKeeper.dat`を見る限り,計算そのものは動作している様に見えます.)

**Comment by k-yoshimi** [comment]
@ultimatile 
ご報告ありがとうございます。
計算を中断するタイミングですが、modpara.defのLanczos_maxで計算したい回数を指定することで可能です。
その一方、現状の仕様を確認したところ、
Lanczos_maxで指定した回数の計算をする前に収束した場合にも、
その先の計算をせずRestart用のベクトルがはき出され終了することがわかりました。
Restart 1の時に6時間走って、Restart 2の時に計算が6分程度とのことですが、
後者の挙動、つまりRestart 1の際にLanczosの計算が終了(エネルギーが収束)している可能性が考えられますが、いかがでしょうか？

なお、後者の仕様はユーザーにとっては動作がわかりづらいものですので、
次のバージョンでは指定した回数以内にエネルギー収束した場合には、
リスタートベクトルをはき出さずに次のステップに進むように修正するようにします。

**Comment by ultimatile** [comment]
ご返信ありがとうございます.
確かに最初の六時間で収束していました.

**Comment by k-yoshimi** [comment]
@ultimatile 
ver.3.0のリリースに際して上記対応いたしましたので、ご確認ください。
また何か不明な点がありましたら、お気軽にご連絡ください。
