### ISSUE TITLE
A freshman problem, and do not clear the meaning of LocalSpin file 

### ISSUE THREAD

**Issue by HengyueLi** [issp-center-dev/HPhi#24]
Dear all,
  I am new to learn Hphi. After finish reading the document, I want to try an easy test, basically a Hubbard(4sites with t and U only). I get error info"Definition files(*.def) are incomplete."  but no details about what is wrong. I feel that I have a wrong setting of LocalSpin file since I do not understand it well. To understand that, is that anyone who can give me an example of the local spin file about this system? By the way, here I upload my setting files.

[HPHI_test.zip](https://github.com/QLMS/HPhi/files/1500614/HPHI_test.zip)

**Comment by mitsuaki1987** [comment]
Dear ggyyuuuu

This message,
```
Read File 'modpara.def' for ModPara.
Error: Definition files(*.def) are incomplete.
```
means that HPhi found syntax error while reading "modpara.def". The correct ModPara file is
```
--------------------
Model_Parameters 0
--------------------
VMC_Cal_Parameters
--------------------
CDataFileHead C22test
CParaFileHead C22testwhatisthis
--------------------
Nsite 4
Ncond 16
2Sz 0
Lanczos_max 1000
initial_iv 12
exct 1
LanczosEps 14
LanczosTarget 2
LargeValue 12
NumAve 5
ExpecInterval 20
```
Comment-out with "#" can not be used in the HPhi input file, and the keyword-value-pair must be written in the same line.

As you feel, the LocSpin file is not correct for the Hubbard system. It should be
```
================================
NlocalSpin   4
================================
========i_0LocSpn_1IteElc ======
================================
0 0
1 0
2 0
3 0
```
"0" at the second column means the itinerant electron.

**Comment by mitsuaki1987** [comment]
I am sorry for my mistake, the comment-out with "#" is accepted.

**Comment by HengyueLi** [comment]
Dear mitsuaki1987,
I use "#" because I think that parameters are not should when CalcType 2. But anyway, even I remove that comments(or remove "#"). It still not works. 
Can you try to run that setting files?

**Comment by mitsuaki1987** [comment]
Can I see your ModPara file ?

**Comment by HengyueLi** [comment]
[HPHI_test.zip](https://github.com/QLMS/HPhi/files/1500728/HPHI_test.zip)
This is all my setting.
And for Modpara:
--------------------
Model_Parameters 0
--------------------
VMC_Cal_Parameters
--------------------
CDataFileHead C22test
CParaFileHead C22testwhatisthis
--------------------
Nsite
4

**Comment by mitsuaki1987** [comment]
Please write the keyword-value pair in the same line, i.e.
```
--------------------
Model_Parameters 0
--------------------
VMC_Cal_Parameters
--------------------
CDataFileHead C22test
CParaFileHead C22testwhatisthis
--------------------
Nsite 4
```

Best regards,
Mitsuaki Kawamura

**Comment by HengyueLi** [comment]
Dear Mitsuaki Kawamura,
 Sorry, I miss the last line.  Suimasen
best,
H Li
