### ISSUE TITLE
Can Single particle Green's function be obtained exactly in Full Diagonalization?

### ISSUE THREAD

**Issue by HengyueLi** [issp-center-dev/HPhi#25]
As asked in the title. Basically, I am following the "User Guide HΦ Version 2.0.4" (EN). I feel a little confused about getting G. I found more than one file which related to G like, OneBodyG(maybe this is the one I need) and SpectrumVec. And I found more than one output file: DynamicalGreen and cisajs. I wonder what is the mechanics to get G by using this package and how to code the setting file?
(Only consider Full Diagonalization)

**Comment by mitsuaki1987** [comment]
OneBodyG: Input file to specify the indices of static G which you want to compute.
SpectrumVec: You should not manipulate this file.
DynamicalGreen: Dynamical G
cisajs: Static G whose indices are specified in OneBodyG

**Comment by HengyueLi** [comment]
and should we do something to CalcSpec in calcmod.def? And aslo SingleExcitation in namelist? Without definition of  SingleExcitation, there are some error information.

**Comment by HengyueLi** [comment]
Then how to output Dynamic G? Should I calculate it myself?

**Comment by mitsuaki1987** [comment]
Please try the tutorial in `samples/Spectrum/Normal/`

**Comment by HengyueLi** [comment]
Thank you for your reply. As I see, this is T=0 case. What I want is finite T calculation. As we know, the Green's function is T dependent quantity and I do not see any T input interface. So I guess maybe I need to calculate that my self. Am I right?

**Comment by mitsuaki1987** [comment]
You are right. HPhi can not compute the Green function, G(\omega), at finite temperature, and you have to compute it manually by using the outputs by FullDiag (or LOBCG). I do not know the explicit procedure for that calculation.

**Comment by HengyueLi** [comment]
thanks anyway.
