### ISSUE TITLE
How can I  obtain the eigenvectors from HPhi?

### ISSUE THREAD

**Issue by fengjsfudan** [issp-center-dev/HPhi#28]
Hi,
   I am a new user of HPhi package and want to get the information of ground state and the first excited wave functions. Based on the manual,   I perform Spin model calculation and set EigenvecIO = "out". zvo_eigenvec_$$_rank_$$.dat will be produced in output folder .   I have written codes to deal with the   zvo_eigenvec_$$_rank_$$.dat, but real part or imaginary of  the wavefunctions  are huge numbers  (see below)
================================================================73197855944786749000000000000000000000000000000000000000000000000000000000000000                                         00000000000000000000000000000000000000000000000000000000000000000000000000000000                                         00000000.000000,-352122293025903060000000000000000000000000000000000000000000000                                         00000000000000000000000000000000000000000000000000000000000000000000000000000000                                         00000000000000000000000000000000000000000000000000000000000000000000000000000000                                         000000000000000000000000000000000000000.000000
-1945367037944072300000000000000000000000000000000000000000000000000000000000000                                         00000000000000000000000000000.000000,-145278324148084050000000000000000000000000                                         00000000000000000000000000000000000000000000000000000000000000000000000000000000                                         .000000
0.000000,-0.000000
-0.000000,3863336503355797200000000000000000000000000000000000000000000000000000                                         00000000000000000000000000000000000000000000000000000000000000000000000000000000                                         0000000000000000000000.000000
-0.000000,0.000000
-887914696465565310000000000000000000000000000000000000000000.000000,-1677895212                                         39943140000000000000000000000000000000000000000000000000000000000000000000000000                                         000000000000000000000000000000000000000000000000000000000000.000000
-633203115419521230000000000000000000000000000000000000000000.000000,-1357614794                                         12528500000000000000000000000000000000000000000000000000000000000000000000000000                                         0000000000000000000000000000000000000000000000000000000000.000000
0.000000,-0.000000
-0.000000,0.000000
================================================================
 what's wrong about my operations? 
 by the way, for MPI calculations, there are many ranks, how are the wave functions organized in different 
rank.

Thanks in advance      

your sincerely 
                                                              JunSheng Feng

**Comment by mitsuaki1987** [comment]
Dear fengjsfudan

I cannot answer without seeing your code.
If you want to manipulate the outputted wave function in your code, it is useful to look at the IO part of the wave function in the source code of HPhi.
http://issp-center-dev.github.io/HPhi/doxygen/_calc_by_l_o_b_p_c_g_8c.html#a318525323fea91c9c78f906b41d20e3b

**Comment by fengjsfudan** [comment]
Thank your response, I attach my code as bellow:


===================================================
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <tgmath.h>
#include <complex.h>
complex double inner_prod(complex double *, complex double *, int );

int main()
{
	FILE *fp;
	char  f_name[] = "zvo_eigenvec_0_rank_0.dat";
	int  num_of_iter,iloop,jloop;
	unsigned long int local_size;
	complex double *data;
	complex double *eigen_vec;
	fp = fopen(f_name,"rb+");
	fread(&num_of_iter, sizeof(int), 1, fp);
	fread(&local_size, sizeof(unsigned long int), 1,fp);
	
	printf("number of interation = %d\n",num_of_iter);
	printf("local_size = %ld\n",local_size);
	eigen_vec = ( complex double *) malloc( (local_size+1) * sizeof(  complex double ) );
	
	
	fread(eigen_vec,sizeof(complex double),local_size+1,fp);
	for(iloop =0 ; iloop <local_size + 1; iloop++)
	{	
		printf("%lf,%lf\n", creal(eigen_vec[iloop]),cimag(eigen_vec[iloop]));

	}
	data = (complex  double*) malloc(10* sizeof( complex double));
	for(jloop = 0 ; jloop < 10; jloop++)
	{
		data[ jloop ] = jloop + jloop * I; 
	}
	printf("==========================================\n");
	
	printf("%lf,%lf\n", creal(inner_prod(eigen_vec,eigen_vec,local_size+1)),\
			cimag(inner_prod(eigen_vec,eigen_vec,local_size+1)));
	printf("===========================================\n");
	printf("%lf,%lf\n", creal(inner_prod(&zcplx,&zcplx,1)), cimag(inner_prod(&zcplx,&zcplx,1)));
	fclose(fp);
	free(eigen_vec);
	return 0;
}


complex  double inner_prod(complex  double *ap, complex  double *bp, int n)
{

	int iloop;
	complex  double sum,sum1;
	sum = 0.0 + 0.0 * I;
	
	for(iloop = 0; iloop < n ; iloop++)
	{
		sum = conj(ap[iloop])*bp[iloop];
		sum1 = sum1 + sum;
	}
	
	return sum1;
}
=======================================================


your sincerely

                                                   JunSheng Feng
