### ISSUE TITLE
Can HPhi calculate the density matrix?

### ISSUE THREAD

**Issue by henhans** [issp-center-dev/HPhi#30]
Dear HPhi team,

I wonder if HPhi supports the calculation of the static density matrix <c^\dagger_i c_j>? 

Thank you!
Tsung-Han

**Comment by yyamaji** [comment]
Dear Tsung-Han:

Thank you for your inquiry.
Yes, you can calculate <c^\dagger_i c_j> at zero and finite temperatures.
We call this kind of observables as (static) Green's function.
Please check our manual for actual calculations.
You can choose the sets of i and j as you like.

Sincerely yours,
Youhei

**Comment by henhans** [comment]
Dear Youhei, Thank you very much! I will try it out.
Best,
Tsung-Han
