### ISSUE TITLE
Using existing eigenvector as an initial vector?

### ISSUE THREAD

**Issue by henhans** [issp-center-dev/HPhi#31]
Dear HPhi Team,

I wonder if it is possible to use an existing eigenvector as an initial vector
for the Lanczos calculation? I am doing a self-consistent calculation (similar
to DMFT) for which the Hamiltonian between the previous and the current
iteration does not change abruptly. It would be ideal to use the converged
Lanczos vector in the previous iteration as an input for the ED calculation
in the current iteration.

Thank you very much in advance!
Best regards,
Tsung-Han

**Comment by k-yoshimi** [comment]
Dear Tsung-Han,

Sorry, HPhi does not support to read a vector as an initial vector. But the implementation of this function to HPhi is easy and I think it is better to implement it at the next minor version.

If you want to use this function soon, please implement it as follows: Add new mode to [SetInitialVector](http://issp-center-dev.github.io/HPhi/doxygen/_lanczos___eigen_value_8c.html#a8fd8da74bd3866447f14f0dc376561f2) function by using [ReadInitialVector](http://issp-center-dev.github.io/HPhi/doxygen/_lanczos___eigen_value_8c.html#a589f87aa6c08653bdff551e16cb825dc ) function. 
Then, set the initial_mode by modifying l. 78-86. in CalcByLanczos.c.
```
       if(X->Bind.Def.initial_iv>0){
          initial_mode = 0; // 0 -> only v[iv] = 1
        }else{
          initial_mode = 1; // 1 -> random initial vector
        }
```
For example, 
X->Bind.Def.initial_iv>0, initial_mode =0,
X->Bind.Def.initial_iv<0, initial_mode =1,
X->Bind.Def.initial_iv=0, initial_mode =2.

Best regards,
Kazuyoshi Yoshimi

**Comment by henhans** [comment]
Dear Yoshimi,
Thank you very much for the instruction! I will dig into the code and try it out.
Anyway, the code is already very fast with amazing parallel scaling!

Best regards,
Tsung-Han

**Comment by mitsuaki1987** [comment]
Dear Tsung-Han

The LOBPCG mode can do this. The input file for Standard mode is as follows:
```
method = "CG"
restart = "restartsave"
:
```
However, please be careful when you perform such a calculation.
If there is a level-crossing (see below), it is possible that you cannot reach the ground state. This is a common problem of the Krylov subspace methods (Lanczos, LOBPCG, ...).
It is safe to start from the random vector.
<img width="407" alt="default" src="https://user-images.githubusercontent.com/11879704/35192455-efe3cd78-fed5-11e7-99c2-edd1ea26f2df.png">

Best regards,
Mitsuaki Kawamura

**Comment by henhans** [comment]
Dear Mitsuaki,
Thank you very much for the instruction! I will pay attention to it.

Best regards,
Tsung-Han
