### ISSUE TITLE
canonical TPQについて

### ISSUE THREAD

**Issue by ultimatile** [issp-center-dev/HPhi#32]
お世話になっております.
HΦのmTPQのデータからcTPQの物理量を計算する際にk=0,すなわち初期ベクトルで計算した物理量が必要になるのですが,出力できるようにしていただけないでしょうか?

**Comment by yyamaji** [comment]
変更箇所をお知らせできると思いますので、
少しお待ちください。

**Comment by ultimatile** [comment]
ご返信ご対応ありがとうございます.
比熱を計算したいのでエネルギーの分散も必要になります.

**Comment by mitsuaki1987** [comment]
@ultimatile 

SS_Rand*にステップ0のエネルギー等を出力するためのパッチをgistに上げました。
https://gist.githubusercontent.com/mitsuaki1987/c403ef12815aff54cd8e515821c27ac0/raw/3530554c305ce675aaaaa8789935e733ed621eca/tpq2.diff
先ほどのパッチに続けてあててください。

**Comment by ultimatile** [comment]
出力できました.ご対応いただきありがとうございました.

**Comment by ultimatile** [comment]
```tpq2.diff```なんですが```v0[i] = v1[i]/dnorm;```の部分は```v0[i] = v1[i];```でよろしいでしょうか？

**Comment by mitsuaki1987** [comment]
@ultimatile 
すみません。その通りでした。直してお使いください。
