### ISSUE TITLE
[tips] slow and non-monotinic convergence of LOBCG

### ISSUE THREAD

**Issue by yyamaji** [issp-center-dev/HPhi#34]
When the target state for the convergence check has (pseudo-)degeneracy,
convergence of LOBCG may becomes slow or shows oscillation of the norm of the residual vector.
If you include every (pseudo-)degenerated states in your target space for the eigenvalues (and eigenvectors), you may obtain better convergence.

**Comment by xuchs07** [comment]
Hi yyamaji,
I indeed run into the problem of convergence when using LOBCG and Lanczos method. Yet, I don't understand what you mean by ``include every (pseudo-)degenerated states in your target space for the eigenvalues (and eigenvectors)''. Could you please further explain it (i.e., what to do when using the HPhi code)? Any paramters or tags in the input file that can be changed to have better convergence?
Thanks in advance,
xuchs07

**Comment by mitsuaki1987** [comment]
Dear @xuchs07 

How about increasing the `exct` parameter for LOBPCG ?

Best regards,
Mitsuaki Kawamura

**Comment by yyamaji** [comment]
Dear @xuchs07

Sorry for delayed response.
What I meant in my entry is as follows:

First of all, my entry based on my experience.
For example, if you apply small amplitude of magnetic fields,
the convergence can be slow.
When your target state is the ground state, since the convergence
of the target eigenstate is affected by the eigenvalue difference
between the first excited state and the target state,
the convergence is determined by the small Zeeman splitting.

Even if there are no applied magnetic fields, there could be
nearly degenerated states.
If your target space (or block Krylov subspace) of LOBCG
only includes one of such nearly degenerated states,
you will suffer from the small gap problem as is expected
under the small magnetic fields.

One possible and practical prescription is increasing
the "exct" parameter as Mitsuaki suggested to include
every nearly degenerated states in the target space.
For the Lanczos method, you may need to accept the
slow convergence.

Sincerely yours,
Youhei

**Comment by yyamaji** [comment]
Dear @xuchs07

P.S. Sorry, I skipped an important basic notion.
If you know well about the followings, please just discard this entry.

Roughly speaking, the "time" scale of convergence of
the Lanczos-type method is expected to be governed
by the smallest eigenvalue difference between the target state
and other eigenstates.

Sincerely yours,
Youhei
