### ISSUE TITLE
possible bug in readdef.c

### ISSUE THREAD

**Issue by tmisawa** [issp-center-dev/HPhi#37]
In readef.c (940th line),
LanczosTarget is checked by the following function:

`ValidateValue(X->LanczosTarget, X->k_exct, X->Lanczos_max)`

This means that
LanczosTarget <= k_exc  &&
LanczosTarget >= Lanczos_max.
But, the second condition is wrong
because LanczosTarget has no relation with Lanczos_max.

**Comment by tmisawa** [comment]
I fixed a bug.
Please check it.

**Comment by k-yoshimi** [comment]
@tmisawa 
This modification seems to be wrong.
When ``X->LanczosTarget > X->k_exct`` , program always be terminated.
Please fix it.

**Comment by tmisawa** [comment]
@k-yoshimi 
> When X->LanczosTarget > X->k_exct , HPhi is always terminated.

I think this is correct,
because HPhi does not calculate the eigenvalues larger than X-> k_exct,

**Comment by k-yoshimi** [comment]
In ver.3.1.0, this bug is fixed.
