### ISSUE TITLE
spinless fermions

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#38]
Good evening to everyone,
I'm a student in theoretical physics at La Sapienza university in Rome and I'm currently trying to run some simulations on hubbard models. My questions are:

1) How can i run a simulation of a non interacting hubbard hamiltonian for a system of SPINLESS fermions? which variables do i have to specify in the input file in standard mode?

2) I would like to simulate a 1D L=10 chain of a non interacting hubbard model with one eigenstate per site and 5 fermions (half filling). Is it correct to specify nelec=1 and ncond=5?

3) Next I would like to compare the analytical results of my calculation of the two-body green function with the one of the program. In the former case the lindhard formula gives me a superposition of delta function for the imaginary part of the two-body green function but when I plot the GF I'm expecting to see two symmetrical peak as compared to the origin. I think i'm doing something wrong

Those are my input files for the standard mode

**scenario.in** ---> input file
L = 10
model = "Fermion Hubbard"
method = "Lanczos"
lattice = "Chain Lattice"

U = 0
mu = 0
t = 1
V = 0     
nelec = 1
Ncond = 5
2Sz = 0

EigenvecIO = "out"

**scenario_gf.in** ---> input file for the calculation of the 2-body GF
L = 10
model = "Fermion Hubbard"
method = "Lanczos"

lattice = "Chain Lattice"

CalcSpec = "Normal"
SpectrumType = "Density"

SpectrumQW = 0
SpectrumQL = 0.628

OmegaIM = -0.1
NOmega = 1000

U = 0
mu = 0
t = 1
V = 0     
nelec = 1
Ncond = 5
2Sz = 0

#I put SpectrumQL = 0.628 because i want to check the 2-body GF for that value of k (k=1) in fractional coordinates. In the non interacting hubbard model the energy is proportional to cos(2 pi n /L) = cos( pi n /5) (L=10)

Thanks for the attention.

**Comment by k-yoshimi** [comment]
@rp092 
Thank you for your question.

>1) How can i run a simulation of a non interacting hubbard hamiltonian for a system of SPINLESS fermions? which variables do i have to specify in the input file in standard mode?
>2) I would like to simulate a 1D L=10 chain of a non interacting hubbard model with one eigenstate per site and 5 fermions (half filling). Is it correct to specify nelec=1 and ncond=5?

The most easy way to run a simulation for spinless fermions is to set the system as full saturated state, i.e.  ``2Sz = Nelec``. For example, in ``scenario.in``, you should modify ``2Sz`` and ``Nelec`` as follows:

```
L = 10
model = "Fermion Hubbard"
method = "Lanczos"
lattice = "Chain Lattice"

U = 0
mu = 0
t = 1
V = 0
nelec = 5
2Sz =5

EigenvecIO = "out"
```

>3) Next I would like to compare the analytical results of my calculation of the two-body green function with the one of the program. In the former case the lindhard formula gives me a superposition of delta function for the imaginary part of the two-body green function but when I plot the GF I'm expecting to see two symmetrical peak as compared to the origin. I think i'm doing something wrong

I think that this problem also originates from setting the wrong values about ``2Sz`` and ``Nelec`` .
Please recalculate by changing the input values.

**Comment by rp092** [comment]
thanks for your answer but my problem still remain: 

By setting the _Spectrumtype_ keyword to “_density_” and the Hubbard’s Hamiltonian as non interacting I can expect the two-body Green’s function calculated by the program to be automatically expressed in the Lindhard form: the **q** vector this function depends on constitute each single-particle exciting energy **k** ---> **k**+**q**

G_2(q;ω) = Σ_k θ(k_F - k) θ(|**k**+**q**| - k_F) [ (ω + ε(k) - ε(k+q) + iδ)^(-1) - ( ω - ε(k) + ε(k+q) - iδ)^(-1) ]

The imaginary part of which is:

Im G_2(q;ω) =  Σ_k θ(k_F - k) θ(|**k**+**q**| - k_F) [ δ(ω - (ε(k+q) -ε(k))) +  δ(ω + (ε(k+q) -ε(k))) ]

Therefore in a L=10 long chain with 5 electrons (half-filling) I expect the imaginary part of said Green’s function to be made up of two peaks which are symmetric to the origin, but this doesn’t happen when I correct the input files as you specify. Where did I go wrong?

thanks for the attention

**Comment by yyamaji** [comment]
@rp092
The denominator of the Lehmann representation of the many-body Green's function
includes chemical potential that is defined through total energy difference among
the ground state with electron number L+1, L, and L-1.
If you include the chemical potential, you may  obtain an expected result.

**Comment by rp092** [comment]
@yyamaji  
So if I'm not wrong μ = 1 in the L=6 and nelec = 3 simulation. Because L = 6 is fixed and the difference in energy between the system with 3 electrons and the one with 4 is exactly 1.

**Comment by yyamaji** [comment]
@rp092
 I think so. Please be careful about the sign change for electron and hole parts.

**Comment by yyamaji** [comment]
@rp092
How about the definition of the density operators?
If you just specify "density", your operator just generate
a hole and electron excitation in your initial state
since it multiplies c^dagger c to the initial wave function.
Therefore, you may only observe positive energy branch
of your Stoner excitations.
I hope it will resolve your problem.

**Comment by yyamaji** [comment]
@rp092
In addition, please be careful about the origin of the frequency.
In the Lindhard formula, the energy origin is expected to be the
ground state energy while, in the HPhi, it will be zero if I remember correctly.
Then, you need to introduce "OmegaOrg" in the expert mode or
please change the origin of the frequency when you plot the data.

**Comment by yyamaji** [comment]
@rp092
Of course, if you modify your expert inputfiles automatically generated after
the standard mode calculation, you can calculate the negative energy branch
by multiplying c c^dagger to the initial wave function.

**Comment by rp092** [comment]
@yyamaji 
1) Thank you so much, you're right μ = -1. Because the energies are -3 and -4 with t = 1
2)So isn't "density" the correct keyword?
at page 39 of the user guide you can see that this is the right specification for the two-body GF
3) I'll check OmegaOrg
4)May I ask one last question? Does the program automatically set the chain’s spacing (a) to 1? If it were the case, in order to observe Green's function for q=2πn/L (n=2 L=6) should I standardize the value only by dividing by 2π, thereby getting as a result q = 0.3?

**Comment by yyamaji** [comment]
@rp092
2) Thank you for your feedback. We may add more explanation in our manucal.
Here, we select keywords to specify the excitation operators and we do not
intend a specific choice of retarded/advanced/causal/... Green's function.
HPhi just perform the Lanczos/CG step starting from the product of the
excitation operators and the initial wave function and calculate spectra.
Therefore, users can chose specific choice of the Green's functions
by combining the HPhi outputs.

About 4), the length scale is based on the lattice vector.
However, SpectrumQL is not a fraction of 2pi.
Please input q=2π m /L (m is an integer).
If you check pair.def after running the standard mode,
you can directly confirm your excitation operators.
Please look at the section 4.2.17 about PairExcitation.

**Comment by rp092** [comment]
Thank you for your answer. So finally my task is to obtain the two body GF of this system

H = Σ_k (-2tcos(k) - μ) c_k* c_k

( * means dagger)
with L = 6 and nelec = 3 (half filling). I know that the GS of that system is the Fermi sea Π_k c_k*|0> for k = 0, +1 -1 ----> |GS> = c_0* c_1* C_1* |0> and the only possible excitations are q= 2,-2 and 3.

I run the first simulation **scenario.in** 
L = 6
model = "Fermion Hubbard"
method = "Lanczos"
lattice = "Chain Lattice"

U = 0
mu = -1
t = 1
V = 0
nelec = 3
2Sz =3

EigenvecIO = "out"

Then the second simulation **scenario_gf.in**
L = 6
model = "Fermion Hubbard"
method = "Lanczos"

lattice = "Chain Lattice"

CalcSpec = "Normal"
SpectrumType = "Density"

SpectrumQW = 0
SpectrumQL = somevalue

OmegaIM = -0.1
NOmega = 1000

U = 0
mu = -1
t = 1
V = 0
nelec = 3
2Sz = 3

I would like to obtain the lindhard GF which output do I have to combine?

**Comment by k-yoshimi** [comment]
@rp092 
OK, thanks.
