### ISSUE TITLE
TUTORIAL

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#39]
**Lecture for HPhi @ Tohoku University**
Usage to calculate dynamical green's functions ----> please tell me that this tutorial exists also in english language

**Comment by k-yoshimi** [comment]
Sorry, there's not english version of "Usage to calculate dynamical green's functions".
(In the near future, I will make it and upload in the official page.)
However, we prepared a sample for spectrum calculation in the following URL.
Though it is for spin system, this information might be useful to see the way to calculate dynamical green's functions by HPhi.
https://github.com/issp-center-dev/HPhi-gallery/tree/master/Spin/HeisenbergSpectrum
