### ISSUE TITLE
Jordan- Wigner transformation betwenn Hubbard and Heisenberg model

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#40]
Good evening to everyone,

I would like to study the hamiltonian

H = -t Σ_i (c*_i+1 c_i + c_i+1 c*_i) + V n_i n_i+1               **(1)**

with μ = 0, U = 0, t=1, V=6t = 6. If one performs an inverse Jordan-Wigner transformation

c c* -----> S_z + 1/2             c* ----> S^+  (S plus)         c ----> S^-   (S minus)

on that hamiltonian he obtains:

H = -t  Σ_i  (S^+_i+1 S^-_i + S^-_i+1 S^+_i)  + V Σ_i (Sz_i + 1/2)(Sz_i+1 + 1/2)

which is equal to an Heisenberg hamiltonian

H = - 2t  Σ_i  (Sx_i+1 Sx_i + Sy_i+1 Sy_i)  + V Σ_i (S^z_i S^z_i+1) + V Σ_i S^z_i  + N V/4          **(2)**

So if I would like to run a simulation for the haniltonian (1) transformed as in (2) i should obtain the same spectrum right? Here is my **input file**

_L = 16
model = "Spin"
method = "Lanczos"
lattice = "Chain Lattice"

Jxy = -2
Jz = 6
D = 0
Gamma = 0
h = -6
2Sz = 0

EigenvecIO = "out"_

But it's easy to see from the fourth column of that **output** that it is not converging and it doesn't stops until the 2000 steps. Where did i go wrong?

######  Start: Calculate Lanczos Eigenvalue.  ######

  initial_mode=1 (random): iv = -1 i_max=12870 k_exct =1 

  LanczosStep  E[1] E[2] E[3] E[4] Target:E[3] E_Max/Nsite
  stp = 2 -7.9808429687 4.6741758885 xxxxxxxxxx xxxxxxxxx xxxxxxxxx xxxxxxxxx 
  stp = 3 -12.4019474881 -1.6839927937 8.9433409528 0.0000000000 8.9433409528 0.5589588096
  stp = 4 -15.7615453140 -6.2089506354 3.0245864383 12.3790318691 3.0245864383 0.7736894918
  stp = 5 -18.3086371649 -9.7258185532 -1.5162910768 6.7329166999 -1.5162910768 0.9580039426
  stp = 6 -20.2421208670 -12.6704358652 -5.2721651249 2.1512808366 -5.2721651249 1.0979430477
  stp = 7 -21.9524224301 -15.3557910086 -8.4584130434 -1.5885425445 -8.4584130434 1.2015909834
  stp = 8 -23.7634256271 -17.7862109096 -11.3355652131 -5.0804685918 -11.3355652131 1.2723573822
  stp = 9 -24.7686683717 -18.8880781923 -12.7435490483 -6.7364605208 -12.7435490483 1.3607289690
  stp = 10 -25.0450750760 -19.2811552987 -13.5766882350 -8.3928801975 -13.5766882350 1.4555434733
  stp = 11 -25.1958920617 -19.7510690980 -15.6989201216 -11.5703379665 -15.6989201216 1.5730806323
  stp = 12 -25.3053661689 -20.7708313951 -17.9975624357 -12.6938518311 -17.9975624357 1.6889916083
  stp = 13 -25.4609569962 -22.7724984588 -18.9806634973 -13.6784050705 -18.9806634973 1.7895874005
  stp = 14 -25.8740722070 -24.3853970741 -19.4145195587 -15.3505756466 -19.4145195587 1.8828783134
  stp = 15 -26.5885400538 -24.9137215461 -19.7867241198 -16.9764538411 -19.7867241198 1.9734500457
  stp = 16 -27.1618978398 -25.0756250829 -20.3712289989 -18.2253652947 -20.3712289989 2.0631135383
  stp = 17 -27.6117124215 -25.1768229675 -21.5790081296 -19.0417689722 -21.5790081296 2.1519086513
  stp = 18 -28.1811700672 -25.3528094735 -23.5681201956 -19.5709379899 -23.5681201956 2.2490487474
  stp = 19 -29.1328341525 -26.0102372775 -24.8016692680 -20.0525511632 -24.8016692680 2.3527859660
  stp = 20 -30.1587295998 -26.6679331346 -25.0211266499 -20.6431741451 -25.0211266499 2.4624910254
  stp = 21 -31.1030192615 -27.1269898125 -25.1249716231 -21.8323571658 -25.1249716231 2.5803920595
  stp = 22 -32.3286762082 -27.7844689590 -25.3656357565 -24.0929633419 -25.3656357565 2.7012236049
  stp = 23 -33.9959443149 -28.8366802054 -26.1695313402 -24.9183905246 -26.1695313402 2.8459443206
  stp = 24 -35.6004039694 -29.7532743319 -26.7035733116 -25.0510839526 -26.7035733116 2.9899985155
  stp = 25 -37.6057223425 -30.9077365750 -27.3370351511 -25.2326389395 -27.3370351511 3.1612309900
  stp = 26 -39.8314856082 -32.3106446048 -28.2584699752 -25.8977358694 -28.2584699752 3.3313882051
  stp = 27 -42.2126054857 -33.8749419850 -29.2657420475 -26.5582756268 -29.2657420475 3.5101714732
  stp = 28 -44.6537501086 -35.5939641363 -30.3449153023 -27.1733175593 -30.3449153023 3.6888868065
  stp = 29 -47.3018126935 -37.6622102148 -31.7405998788 -28.1182865767 -31.7405998788 3.8714657765
  stp = 30 -50.0347692214 -39.8710366677 -33.2510800243 -29.1280250849 -33.2510800243 4.0596080313
  stp = 31 -52.7520274837 -42.1137754212 -34.8761655811 -30.2099883967 -34.8761655811 4.2438192642
  stp = 32 -55.6412763339 -44.6125209560 -36.8906279135 -31.6455160776 -36.8906279135 4.4359527541
  stp = 33 -58.4333392825 -47.0698028934 -38.9264088801 -33.0758369379 -38.9264088801 4.6224131963
  stp = 34 -61.3829884112 -49.7301920955 -41.1908579214 -34.7800123660 -41.1908579214 4.8185286222
  stp = 35 -64.3882428892 -52.4324394999 -43.5302140623 -36.6908050930 -43.5302140623 5.0161151058
  stp = 36 -67.5173690336 -55.1851529177 -45.9544110920 -38.7399513936 -45.9544110920 5.2234141043
  stp = 37 -70.7679128368 -57.9948908190 -48.5044930135 -40.9557641850 -48.5044930135 5.4358649657
  stp = 38 -74.1261335522 -60.8642120045 -51.1363463522 -43.2566750072 -51.1363463522 5.6553739459
  stp = 39 -77.5563100477 -63.7995661041 -53.8110245613 -45.6311040350 -53.8110245613 5.8789729951
  stp = 40 -81.0942009529 -66.8677230241 -56.5695226539 -48.1472336908 -56.5695226539 6.1075881770
  stp = 41 -84.7044635675 -70.0265059005 -59.3549080598 -50.7129449766 -59.3549080598 6.3415891388
  stp = 42 -88.4336253887 -73.3072416679 -62.2306363681 -53.3682726348 -62.2306363681 6.5811720723
  stp = 43 -92.3249321532 -76.7122570670 -65.2214082677 -56.0931868555 -65.2214082677 6.8312137346
  stp = 44 -96.3386784402 -80.1746722352 -68.2835319867 -58.8358861838 -68.2835319867 7.0880229177
  stp = 45 -100.5982028092 -83.8039459043 -71.5283877366 -61.7229226174 -71.5283877366 7.3595125739
  stp = 46 -104.9568015149 -87.4670102537 -74.8029311137 -64.6234574212 -74.8029311137 7.6371428318
  stp = 47 -109.5668012649 -91.3415213013 -78.2634526736 -67.7194775974 -78.2634526736 7.9295674552
  stp = 48 -114.2436834561 -95.2822569248 -81.7407349065 -70.8458387697 -81.7407349065 8.2263725584
  stp = 49 -119.1249081835 -99.4500778589 -85.3891542196 -74.1507988014 -85.3891542196 8.5355572132
  stp = 50 -124.0678696101 -103.7192551889 -89.0949050737 -77.4991714009 -89.0949050737 8.8485898635
  stp = 51 -129.1747380475 -108.1866255556 -92.9732852111 -80.9853452392 -92.9732852111 9.1721233194
  stp = 52 -134.3708614325 -112.7660138225 -96.9661588580 -84.5417580465 -96.9661588580 9.5009280721
  stp = 53 -139.7229008008 -117.5018420153 -101.1319163060 -88.2263453357 -101.1319163060 9.8400876228
  stp = 54 -145.2034293214 -122.3495821444 -105.4365679194 -92.0234788100 -105.4365679194 10.1868537136
  stp = 55 -150.8554329176 -127.3343966718 -109.8989835473 -95.9685369074 -109.8989835473 10.5449597554
  stp = 56 -156.6647379282 -132.4355764064 -114.4901276736 -100.0525831066 -114.4901276736 10.9125669703
  stp = 57 -162.6656124655 -137.6835176345 -119.2246411666 -104.2973603276 -119.2246411666 11.2925718885
  stp = 58 -168.8327024808 -143.0585582258 -124.0707008343 -108.6732972968 -124.0707008343 11.6828385100
  stp = 59 -175.2039634272 -148.6050925835 -129.0617698253 -113.2065044030 -129.0617698253 12.0860298062
  stp = 60 -181.7341423522 -154.2888030520 -134.1586125825 -117.8476928273 -134.1586125825 12.4992227544
  stp = 61 -188.4717750149 -160.1665317840 -139.4172408293 -122.6419116813 -139.4172408293 12.9253242992
  stp = 62 -195.3544117711 -166.1846905912 -144.7879640813 -127.5296363816 -144.7879640813 13.3606754229
  stp = 63 -202.4421851909 -172.4082055897 -150.3414810441 -132.5760757698 -150.3414810441 13.8086527372
  stp = 64 -209.6626576779 -178.7684679865 -156.0167557280 -137.7177692314 -156.0167557280 14.2651348719
  stp = 65 -217.0848469493 -185.3349953097 -161.8895209390 -143.0322330495 -161.8895209390 14.7339763975
  stp = 66 -224.6330897027 -192.0316842318 -167.8895697152 -148.4535149211 -167.8895697152 15.2108607856
  stp = 67 -232.3817613414 -198.9305410563 -174.0920644419 -154.0620142767 -174.0920644419 15.7000338586
  stp = 68 -240.2560649158 -205.9540432429 -180.4217871527 -159.7885216456 -180.4217871527 16.1971400920
  stp = 69 -248.3333714062 -213.1758774965 -186.9523112199 -165.7108472777 -186.9523112199 16.7067411176
  stp = 70 -256.5408301029 -220.5198633680 -193.6068926986 -171.7562634566 -193.6068926986 17.2244670266
  stp = 71 -264.9582622089 -228.0618481915 -200.4591979780 -177.9998479069 -200.4591979780 17.7551804850
  stp = 72 -273.5134323665 -235.7267014170 -207.4320848882 -184.3656690329 -207.4320848882 18.2944131336
  stp = 73 -282.2896397300 -243.5940110121 -214.6020825203 -190.9292682640 -214.6020825203 18.8473776931
  stp = 74 -291.2124363566 -251.5874078280 -221.8904832991 -197.6111720801 -221.8904832991 19.4093541461
  stp = 75 -300.3706052788 -259.7924702662 -229.3796920480 -204.4915028636 -229.3796920480 19.9859986123
  stp = 76 -309.6840387122 -268.1283725054 -236.9868960134 -211.4857701876 -236.9868960134 20.5721575051
  stp = 77 -319.2493891756 -276.6891100866 -244.8031932028 -218.6823860032 -244.8031932028 21.1740434664
  stp = 78 -328.9775074614 -285.3860552448 -252.7386877470 -225.9896396219 -252.7386877470 21.7858918672
  stp = 79 -338.9752237104 -294.3238306716 -260.8955276454 -233.5070965446 -260.8955276454 22.4145837628
  stp = 80 -349.1414814031 -303.4030464710 -269.1739506005 -241.1335171397 -269.1739506005 23.0535931769
  stp = 81 -359.5952275970 -312.7407107232 -277.6889074008 -248.9815923152 -277.6889074008 23.7105654284
  stp = 82 -370.2213819978 -322.2243725370 -286.3285156152 -256.9385746286 -286.3285156152 24.3781024422
  stp = 83 -381.1524281669 -331.9846386121 -295.2216438433 -265.1314411660 -295.2216438433 25.0646848838
  stp = 84 -392.2579584743 -341.8944636046 -304.2426962606 -273.4344830740 -304.2426962606 25.7619751873
  stp = 85 -403.6848461390 -352.0987240893 -313.5349863739 -281.9894390705 -313.5349863739 26.4793319891
  stp = 86 -415.2868122487 -362.4549982375 -322.9582830432 -290.6567470737 -322.9582830432 27.2074518618
  stp = 87 -427.2254308600 -373.1226174469 -332.6703804852 -299.5928410266 -332.6703804852 27.9565857046
  stp = 88 -439.3386469982 -383.9436640506 -342.5161059054 -308.6439355232 -342.5161059054 28.7164728413
  stp = 89 -451.8025736143 -395.0917012083 -352.6673887222 -317.9806951362 -352.6673887222 29.4982451671
  stp = 90 -464.4399662341 -406.3937301798 -362.9543312260 -327.4351941925 -362.9543312260 30.2907206640
  stp = 91 -477.4409336009 -418.0369990110 -373.5623729958 -337.1915936255 -373.5623729958 31.1058797579
  stp = 92 -490.6139723378 -429.8342359058 -384.3075203217 -347.0682859045 -384.3075203217 31.9316744454
  stp = 93 -504.1623613980 -441.9855849175 -395.3879030008 -357.2620275867 -395.3879030008 32.7808850579
  stp = 94 -517.8814829953 -454.2905690293 -406.6063571177 -367.5782814882 -406.6063571177 33.6406653419
  stp = 95 -531.9867718920 -466.9612726185 -418.1727549450 -378.2254078308 -418.1727549450 34.5245357630
  stp = 96 -546.2617489705 -479.7852270198 -429.8778768625 -388.9969032745 -429.8778768625 35.4189260976
  stp = 97 -560.9328829348 -492.9854004600 -441.9423148609 -400.1116995189 -441.9423148609 36.3380305360
  stp = 98 -575.7731158978 -506.3386023260 -454.1460040587 -411.3524227782 -454.1460040587 37.2676312372
  stp = 99 -591.0187867606 -520.0775826317 -466.7192002504 -422.9475372742 -466.7192002504 38.2225268147
  stp = 100 -606.4335156920 -533.9696896255 -479.4322266408 -434.6699563679 -479.4322266408 39.1879270380
  stp = 101 -622.2623554711 -548.2563511473 -492.5239469443 -446.7566534862 -492.5239469443 40.1791656449
  stp = 102 -638.2607999694 -562.6966629107 -505.7562759954 -458.9719912654 -505.7562759954 41.1809520056

**Comment by k-yoshimi** [comment]
Hi, @rp092 
Jxy is used to represent the term ``` S_i^x S_{i+1}^y +h.c.```.
In this case, Sz is not conserved. As a result, the calculation of HPhi for Sz conserved spin system is not converged.
 
To represent the hamiltonian you gave, you modify the input file like this: 
```
L = 16
model = "Spin"
method = "Lanczos"
lattice = "Chain Lattice"
Jx = -2
Jy = -2
Jz = 6
D = 0
Gamma = 0
h = -6
2Sz = 0

EigenvecIO = "out"
```

Best regards

**Comment by rp092** [comment]
good evening @k-yoshimi , thanks for your reply. I have another question for the HPhi team:

1) the input file which i'm intrested in is the one that you specify in your reply. When I run my simulation of the heisenberg hamiltonian the output on screen is

  Process element info
    Process       Dimension   Nup  Ndown  Nelec  Total2Sz   State
          0           12870     8      8      8         0  

so my question is? shouldn't the number of electrons be equal to 16 instead of 8?

2) I'm trying to reproduce the results given in the paper by **Gagliano and Balseiro** _Dynamical properties of quantum many-body systems at Zero Temperature_  published on **Phys. Rev. Letters volume 59 number 26 (1987) page 2999**. 

Thanks to Jordan-Wigner transformation i should obtain the same Dynamical Green function results as if I use an hubbard hamiltonian related to that input files

**scenario_hubbard.in**

>L= 16
>model = "Fermion Hubbard"
>method = "Lanczos"
>lattice = "Chain Lattice"

>U = 0
>mu = 0
>t = 1
>V = 6     
>nelec = 8
>2Sz = 8

>EigenvecIO = "out"`

**scenario_gf.in**
>L = 16
>model = "Fermion Hubbard"
>method = "Lanczos"
>lattice = "Chain Lattice"

>CalcSpec = "Normal"
>SpectrumType = "Density"

>SpectrumQW = 0
>SpectrumQL = 0.25

>OmegaIM = -0.1
>NOmega = 5000

>U = 0
>mu = 0
>t = 1
>V = 6     
>nelec = 8
>2Sz = 8

...as if I use an Heisenberg hamiltonian related to that input files

**scenario_Heisenberg.in**
>L = 16
>model = "Spin"
>method = "Lanczos"
l>attice = "Chain Lattice"

>Jx = -2
>Jy = -2
>Jz = 6
>D = 0
>Gamma = 0
>2Sz = 0

>EigenvecIO = "out`

**scenario_gf.in**
>L = 16
>model = "Spin"
>method = "Lanczos"
>lattice = "Chain Lattice"

>CalcSpec = "Normal"
>SpectrumType = "SzSz"

>SpectrumQW = 0
>SpectrumQL = 0.25

>OmegaIM = -0.1
>NOmega = 5000

>Jx = -2
>Jy = -2
>Jz = 6
>D = 0
>Gamma = 0
>2Sz = 0

The Gagliano and Balseiro results are in good agreement with the first simulation (Hubbard Hamiltonian)
but not with the second one. Here are the green functions for k = pi/2 

![hubbard](https://user-images.githubusercontent.com/38993526/40112307-e24011c4-5905-11e8-9165-a8d85c6a7d3b.png)

![heisenberg](https://user-images.githubusercontent.com/38993526/40112428-36bbd40e-5906-11e8-96b4-027c520e7f3e.png)

as you can see from those images the frequencies of the excitation are commensurate but in the second plot it seems as if there is a problem in the convergence of the lanczos algorithm. Can you help me?

Thanks a lot.
Riccardo

**Comment by rp092** [comment]
A similar thing also happens in the non interacting case. Here are the two dynamical green functions plot

![hubbard](https://user-images.githubusercontent.com/38993526/40113491-f121ac1c-5909-11e8-8ae4-aad3de6411e2.png)

![heisenberg](https://user-images.githubusercontent.com/38993526/40113492-f1428c7a-5909-11e8-9674-396e6d882a2a.png)

**Comment by k-yoshimi** [comment]
@rp092 
>1) the input file which i'm intrested in is the one that you specify in your reply. When I run my simulation of the heisenberg hamiltonian the output on screen is  
  Process element info
    Process       Dimension   Nup  Ndown  Nelec  Total2Sz   State
          0           12870     8      8      8         0    
so my question is? shouldn't the number of electrons be equal to 16 instead of 8?

Yes, you're absolutely right. HPhi ver. 3.0.0  output the number of ``Nup`` as ``Nelec`` on Spin system. We've already fixed this problem and fixed version will be released.

We'll investigate the second problem. Please wait for a moment.

**Comment by k-yoshimi** [comment]
@rp092 
By using Jordan-Wigner transition, we must consider the boundary factor -1 under the periodic boundary condition (there are 7 electrons when electron moves 0-th to 15-th site).   
Since this contribution is lacked in the input file for spin system, the eigenvalue is not same as that obtained for Hubbard model. As a result, the spectrum became different one.
You can solve this problem by the following process.

1. make definition files by using dry mode.
```
$ HPhi -sdry scenario_Heisenberg.in
```

2. modify the last line in exchange.def file from `` 15     0       - 1.000000000000000 ``  to `` 15     0        1.000000000000000``. 

3. run Hphi by expert mode.
```
$ HPhi -e namelist.def
```

Like this, you should modify the exchange.def file generated by ``scenario_gf.in `` file before running Hphi to calculate spectrum function.

But I think that it is better to choose the anti periodic boundary condition for Hubbard model because the model generated by this input file does not become closed shell system. You can easily set the boundary condition by using the keyword `phase0`  in the input file. See the manual for details.

Best regards.

**Comment by rp092** [comment]
>By adding constant term NV/4 = 24, you can see that the eigenvalue becomes same as that obtained for Hubbard model. 

Yeah you're right professor. Indeed I realized there was some problem in the convergence because the two energies were approximately shifted by 24 units. So the GS was quite right but not the spectrum, that made me quite suspicious.

thanks for the investigation, now my simulation are equal and i can continue on my degree thesis.
Thanks a lot.

Riccardo
