### ISSUE TITLE
Standard mode with magnetic field for all models?

### ISSUE THREAD

**Issue by TMueller83** [issp-center-dev/HPhi#42]
Hi,

I wonder why in standard mode one can only use a magnetic field for the spin model. Some time ago I already asked if it would be possible to include a magnetic field in the Hubbard model and Mitsuaki Kawamura kindly gave me a patch for StdFace. This patch worked well in v2.0.0 but in v3.0.0 it does not work anymore. Would it not be useful to give the user the possibility to include a magnetic field in all models of the standard mode?

Anyways your program is a great tool and I thank you for sharing it with the world!

Best regards,
Tobias.

**Comment by mitsuaki1987** [comment]
Dear TMueller83
Hello,
That patch is already included in v3.0.0. However, the manual is not updated. Thank you.
Best regards,
Mitsuaki Kawamura

**Comment by TMueller83** [comment]
Hello Mitsuaki Kawamura,

okay that is very cool. Thank you!

Best regards,
Tobias.

**Comment by k-yoshimi** [comment]
From ver. 3.1, the incorrect description is fixed.
