### ISSUE TITLE
Staggered Potential

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#45]
Good Evening to everyone.
This is the SPINLESS Hamiltonian that I would like to simulate:

H = Δ Σ_ j (-1)^j c*_ j c_ j - t Σ_ j (c*_ j+1 c_ j + H.c) + V Σ_ j n_ j n_ j+1 

where * means dagger. As you can see the first term is equivalent to a staggered potential that lifts or lowers the energy of site j depending on its value (odd or even). In _expert mode_ it is possible to modify the _trans.def_ file which contains the value of the transfer integrals. Is it possible to integrate in that file the value Δ for i = j sites o does it exist a better choice?

Thanks for the attention

Riccardo Piombo.

**Comment by k-yoshimi** [comment]
Hi @rp092 
There used to be a file that defines chemical potential, but now there is no longer. 
So, to add staggered potential, please use ` trans.def` file as you described.
For example, the one-body potential can be added as follows 
(here, it is assumed that the system is fully saturated):
```
1 0 1 0 1.0
2 0 2 0 -1.0
3 0 3 0 1.0
4 0 4 0 -1.0
...
```
Do not forget to change the total number of transfer integrals defined at 2nd line in `Trans` file.

Best regards,
Kazuyoshi Yoshimi
