### ISSUE TITLE
HΦ v3.1.0 make test error

### ISSUE THREAD

**Issue by yoshizk07** [issp-center-dev/HPhi#50]
下記のように、HΦ v3.1.0 をビルドした後、
make test をすると下記のようなエラーが出ます。
原因はわかりますでしょうか？

0. コンパイラ
  Intel 2017.4.196
または
  Intel 2018.1.163
を使用
  （いずれを使用してもエラーが出ます）

mkdir build; cd buildののち
2. cmakeのオプション
  cmake .. -DCONFIG=intel -DUSE_SCALAPACK=ON（ScaLAPACK使用時）
または
  cmake .. -DCONFIG=intel （ScaLAPACK非使用時）
を使用 
 （いずれの場合もエラーが出ます）
3. make
4. make test MPIRUN="mpiexec -np 4" などとして並列テストを実行
　47ケースが実行され、そのうち5ケースがエラー終了が表示されます。

（略）
42/47 Test #42: te_pulse_hubbard_square ..............***Failed    7.71 sec
     Start 43: te_quench_hubbard_square
（略）
44/47 Test #44: te_hubbard_chain_interall ............***Failed    0.53 sec
     Start 45: te_hubbard_chain_interall_diagonal
45/47 Test #45: te_hubbard_chain_interall_diagonal ...***Failed    0.52 sec
     Start 46: te_spin_chain_interall
46/47 Test #46: te_spin_chain_interall ...............***Failed    0.52 sec
     Start 47: te_kondo_chain_interall
47/47 Test #47: te_kondo_chain_interall ..............***Failed    0.52 sec

**Comment by yoshizk07** [comment]
上記の件に追加ですが、
上は４並列での実行ですが、１６並列で実行しても同様です。

-O0（最適化無し）にしても、エラーが出ることを確認しました。

ソースコード、入力データ、比較用データ、或いは手順（make test
を実行すること自体がまずい）のいずれかに問題があるのではないかと
考えています。

**Comment by k-yoshimi** [comment]
@yoshizk07 
並列計算しない(1並列)場合にはうまくテストが通るのでしょうか？

**Comment by k-yoshimi** [comment]
@yoshizk07 
こちらではテストが通っているので環境の再現ができません.
ひとまず, buildしたディレクトリ下に
``test/te_pulse_hubbard_square``
があると思うのですが、そこで直接
``mpirun -np 4 HPhi -s stan.in``
を実行した場合にどのようなエラーメッセージが出るかご連絡いただけるでしょうか？
もしここでエラーが出ていないのだとすれば、比較用データとの不一致が出ていると思います.
その場合は, outputフォルダより下のデータを送っていただけると助かります.
よろしくお願いします.

**Comment by k-yoshimi** [comment]
``make test`` の代わりに ``ctest -R "te_pulse_hubbard_square" -VV`` としていただいて、
その結果をいただけるでしょうか？

**Comment by k-yoshimi** [comment]
@yoshizk07 

- 並列計算しない(1並列)場合のテスト
- ctest -R "te_pulse_hubbard_square" -VV

の二つだけで十分です(2つ目はログを見たいだけでしたので, ctest -VVと同じ処理になるためです)。

**Comment by yoshizk07** [comment]
v3.1.1 
https://github.com/issp-center-dev/HPhi/releases/download/v3.1.1/HPhi-3.1.1.tar.gz
を intel コンパイラ 2017 と 2018 で試しました。

V3.1.0：42, 44, 45, 46, 47の5ケースがエラー
V3.1.1：13～24, 44, 45, 46, 47の16ケースがエラー

でエラーの数が増えました。

しかし、V3.1.1 では、42番だけはエラーが出なくなりました。

**Comment by k-yoshimi** [comment]
@yoshizk07 
ありがとうございます. v3.1.1でLOBCGでエラーが起きましたか.
ひとまず, v3.1.1の44-47の実時間発展を潰そうと思います. 
今日・明日は別件対応があるため, 明後日ご連絡いたしますので, 少々お待ちください.

**Comment by mitsuaki1987** [comment]
吉澤さま

``` bash
$ tar czvf test.tar.gz test Testing
```
で出てきたファイルを集めてどこかにアップロードして共有するのは可能でしょうか？

河村光晶

**Comment by yoshizk07** [comment]
どこかにファイルの置き場があれば可能ですが、
その置き場を利用するには、
アカウントを作ってログインしてもらわないといけませんか？

どこかのメールアドレスに送るのではダメですか？

**Comment by mitsuaki1987** [comment]
吉澤さま
googleを想定していましたが、もしそれほど重くなければ私のメールアドレスに送って頂いても良いです。
どうぞよろしくお願いします。

**Comment by mitsuaki1987** [comment]
吉澤さま
すみません、CMakeCache.txtも追加でお願いします。

**Comment by yoshizk07** [comment]
こちらもすみません。

テスト44～47については、一時的にnumpyの
パスを外していた（numpyの必要性を確認するため）ことが原因でした。

従いまして、以下が正しい情報です。
V3.1.0：42番がエラー
V3.1.1：13～24番がエラー

**Comment by k-yoshimi** [comment]
@yoshizk07
teの残りはpythonを使用していたので、pythonの環境も疑っておりましたが、無事取れたとのことで安心しました。
(python2,3で動くようにしていたので、少し不思議ではあったのですが)

@mitsuaki1987
zvo_energyの計算でずれる点、原因究明ありがとうございます。時間のあるときに、私の方でも探ってみます。

**Comment by k-yoshimi** [comment]
@yoshizk07 @mitsuaki1987 
さきほどメールでお送りしましたが, developブランチの最新版にbugfixしたものをアップしました.
phys.cのfulldiagのscalapackコード分岐がきちんと処方されていませんでした.
ご確認いただいた上で、問題ないようでしたらv3.1.2として修正したものをリリースするようにします.

**Comment by mitsuaki1987** [comment]
@k-yoshimi 
今gccで試してみたのですが、やはり報告にある通りrestartのテストが失敗します。
原因はおそらく次の通りです。
収束しなかった時にリスタート用の波動関数を出力するのですが、それが終わる前に`exitMPI`で強制終了しているので、次に再計算するときに波動関数の読み込みで落ちるようです。

**Comment by yoshizk07** [comment]
これはすぐに修正可能ですか？

**Comment by k-yoshimi** [comment]
https://github.com/issp-center-dev/HPhi/tree/bugfix_restart
こちらのページに行っていただき、downloadを押すと一式ダウンロードできるかと思います.

p.s. 上のページへの行き方ですが,
https://github.com/issp-center-dev/HPhi
でbranchというのが左に表示されていますが、そこで「bugfix_restart」を選ぶと上のページにいきます。

**Comment by mitsuaki1987** [comment]
@k-yoshimi 
bugfix_restartブランチでte_ac_hubbard_squareのテストを実行すると、テスト自体は成功しているのですが、ログを見るとHPhiはexitMPIで強制終了されています。
これは良いのでしょうか？

また、HPhiMain.cで
``` c
  stdoutMPI = stdout;
  if(JudgeDefType(argc, argv, &mode)!=0){
      exitMPI(0);
  }
```
のように戻り値を0にして強制終了していますが、これですとプログラムの戻り値を`$?`で見た時に正常に終了しているように錯覚してしまうため、0ではない戻り値になるようにした方が良いと思います。

**Comment by mitsuaki1987** [comment]
@k-yoshimi 
時間発展計算なので、おそらく
``` c
      case TimeEvolution:
        if(CalcByTEM(X.Bind.Def.Param.ExpecInterval, &X)!=0){
            exitMPI(0);
        }
```
で止まったものと思われますが、強制終了時に理由が出力されないのはあまりよくないと思います。

**Comment by k-yoshimi** [comment]
@mitsuaki1987 
はい、ご指摘通りですね。後日対応しておきます。
teについてはexitMPI(0)で抜ける理由がわかったので、さきほど修正をpushしました。

**Comment by yoshizk07** [comment]
ちなみに、この bugfix_restart versionはいくつでしょうか？
実行の時に表示される version と一致していますか？

**Comment by k-yoshimi** [comment]
@yoshizk07 
releaseブランチでbugをとったため、次のバージョンの3.1.2が表示されています。

**Comment by k-yoshimi** [comment]
v3.1.2をリリースしたのでcloseします。
色々とご報告いただき、助かりました。
今後ともよろしくお願いします。
