### ISSUE TITLE
_OPENMPマクロにつきまして

### ISSUE THREAD

**Issue by mitsuaki1987** [issp-center-dev/HPhi#51]
@k-yoshimi 
しばらく前からコンパイル時に
``` bash
[  5%] Building C object src/CMakeFiles/HPhi.dir/FileIO.c.o
<command-line>:0:0: warning: "_OPENMP" redefined
<built-in>: note: this is the location of the previous definition
```
のような警告が出るようになり、調べてみるとコミット
c3fcaf0c01cb578c9ee83ae3b13e8546ccf48685
で`_OPENMP`のマクロを手動で付けるようにしていました。
この`_OPENMP`ですが、使用かどうかは分かりませんが普通はコンパイラが自動でOpenMPのバージョン番号として定義していて、例えば
``` c
#include <stdio.h>
int main(int argc,  char *argv[])
{
  printf("_OPENMP = %d\n", _OPENMP);
}
```
というソースを手元のPCで`-fopenmp`をつけてgccでコンパイルすると
```
_OPENMP = 201511
```
と出ます。HPhiではやっていませんが、これでOpenMPのバージョンによって切り替えたりするのに使うそうです。
あまり手動で定義しない方が良いマクロではないかと思いますが、こうしなければならない場合があったのでしょうか？

**Comment by k-yoshimi** [comment]
@mitsuaki1987 
コメントありがとうございます。確かに不必要なので消しました。
