### ISSUE TITLE
Correlation Functions

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#53]
Hi everyone!
I want to compute that correlation function:

 C(r) = 1/N sum_i <k_i k_i+r> - <k_i>^2                   (1)

where r specifies a site of the chain. Thanks to the translational invariance of my system I can neglect the sum and just compute one of its terms at fixed i. Let's say that i=1 and that my system is a linear chain of fermions at half filling with hopping terms, staggered potential, nearest neighbour repulsion and next nearest neighbour repulsion only on the even sites:

H = Δ/2 Σ_ j (-1)^j c*_ j c_ j - t Σ_ j (c*_ j+1 c_ j + H.c) + Vpd Σ_ j n_ j n_ j+1 + Vpp Σ_ j n_ j n_ j+2 

So, given that

k_i = C*_i+1 C_i + H.c 

it results:
k_1 k_1+r   =   C*_1 C_2 C*_1 +r C_2+r    +     C*_1 C_2 C*_2+r C_1+r    +     C*_2 C_1 C*_1+r C_2+r    +    C*_2 C_1 C*_2+r C_1+r

k_1  =   C*_1 C_2   +   C*_2 C_1

So, for example, if L=6 the file GREENTWO.DEF is

=============================================
NCisAjsCktAltDC        24
=============================================
======== Green functions for Sq AND Nq ======
=============================================
    1     0     2     0     1     0     2     0
    1     0     2     0     2     0     1     0
    2     0     1     0     1     0     2     0
    2     0     1     0     2     0     1     0
    1     0     2     0     2     0     3     0
    1     0     2     0     3     0     2     0
    2     0     1     0     2     0     3     0
    2     0     1     0     3     0     2     0
    1     0     2     0     3     0     4     0
    1     0     2     0     4     0     3     0
    2     0     1     0     3     0     4     0
    2     0     1     0     4     0     3     0
    1     0     2     0     4     0     5     0
    1     0     2     0     5     0     4     0
    2     0     1     0     4     0     5     0
    2     0     1     0     5     0     4     0
    1     0     2     0     5     0     0     0
    1     0     2     0     0     0     5     0
    2     0     1     0     5     0     0     0
    2     0     1     0     0     0     5     0
    1     0     2     0     0     0     1     0
    1     0     2     0     1     0     0     0
    2     0     1     0     0     0     1     0
    2     0     1     0     1     0     0     0

While the file GREENONE.DEF is:

===============================
NCisAjs         2
===============================
======== Green functions ======
===============================
    1     0     2     0
    2     0     1     0

Next i run Hphi after modyfing appropriately the Coulombinter.def and the trans.def files, applying some maths with python to the output I should obtain what in Eq.(1) at fixed i. 

Does it exist a more direct way to compute correlation function with Hphi without writing a bash code to manipulate the .def file in question?

**Comment by k-yoshimi** [comment]
@rp092 
The calculation you did was not supported in the standard mode of HPhi, I think.
So, you must directly define Green's functions by *.def files as you did.

**Comment by rp092** [comment]
Taking the same hamiltonian

H = Δ/2 Σ_ j (-1)^j c*_ j c_ j - t Σ_ j (c*_ j+1 c_ j + H.c) + Vpd Σ_ j n_ j n_ j+1 + Vpp Σ_ j n_ j n_ j+2

When Vpd = 0 and Vpp, Delta >> t  the GS energy is the represented by the two straight lines (orange and green) in the figure. Indeed, in that limit, when Δ > 0, E_gs = -NΔ/2 and in the Δ<0 case E_gs = N(Δ/2 + Vpp). As you can see the Energy in the plot should be equal to E_gs of the two phases asimptotically in Δ, but it doesn't happen.

![figure_1](https://user-images.githubusercontent.com/38993526/49435491-0a60ec00-f7b7-11e8-9060-a306b920bad0.png)

Is there any problem with the input files? I noted that when i put Vpd=0 the transition point at Δ=-Vpp suddenly moves to Δ=0 !!!! (WHY?)

So in the simulation i put Vpd=0.01 to avoid this strange behaviour.

Here is my code
-------------------------------------------------------------------------------------------------------------------------------------------

#!/bin/bash
export LC_NUMERIC="en_US.UTF-8"

if [ $# -ne 6 ]
then
    echo "Pass me the scenario.in as 1st argument."
    echo "Pass me Vpd as 2nd argument."
    echo "Pass me delta_start as 3th argument."
    echo "Pass me Delta_delta as 4th argument."
    echo "Pass me delta_end as 5th argument."
    echo "Pass me Vpp as 6th argument."
    exit
fi

#input file 

input=$1

#interaction Silver-Fluorine

Vpd=$2

#staggered potential

delta_start=$3
Delta_delta=$4
delta_end=$5

#Fluorine-Fluorine interaction

Vpp=$6

#Get L from the input

L=`cat $input | grep "L" | awk -F "=" '{name=$1; value=$2; gsub(" ", "", name); gsub(" ", "", value); if (name == "L") print value}'`

#Get t from the input

t=`cat $input | grep "t" | awk -F "=" '{name=$1; value=$2; gsub(" ", "", name); gsub(" ", "", value); if (name == "t") print value}'`
echo "chain lenght = $L"

mkdir -p energy_results
cp $input energy_results
cp header_CI.def energy_results
cd  energy_results

destdir1=Delta.dat
destdir2=Energy.dat
#--------------------------------------------------------------------------------------
#Computation of the ground state energy
#--------------------------------------------------------------------------------------

for delta in `seq $delta_start $Delta_delta $delta_end`
do
#--------------------------------------------------------------------------------------
#Dry run
#--------------------------------------------------------------------------------------

    rm -f trans.def
    rm -f coulombinter.def
    rm -f greentwo.def
    rm -f greenone.def
    echo "$delta" >> "$destdir1"
    echo "delta=$delta"
    
    # Change the value of V in scenario.in with the value of Vpd (1st neighbour interaction)

    cat $input | sed 's/YYY/'$Vpd'/g' > scenario_Vpd_$Vpd.in
    
    #Print on file what is written on screen during the dry run

    HPhi -sdry scenario_Vpd_$Vpd.in > output-sdry_$Vpd
    
    echo "Dry run finshed"
#------------------------------------------------------------------------------------------------
#Generate the trans.def---> file with the staggered potential (-1)^l * Delta/2

#note that the first term of Delta/2 sum_l (-1)^l+1 n_l it's negative (l=0) but in HPhi the t_ij terms 
#are defined with a minus sign beyond ---> - sum_{ij} t_{ij}(c*_i c_j)
#so, in that case, l=0 is a Flourine site (positive Delta)
#------------------------------------------------------------------------------------------------

#s1 s2 spin in the two sites (you have to specify the value of Delta both for spin up and spin down cases)

    cat > generate_trans.py <<EOF
for j in range($L):
   sign = ((-1)**(j+1))/2.
   for s1 in range(2):
      for s2 in range(2):
         line = "%5d %5d %5d %5d%26.15f%26.15f" % (j, s1, j, s2, sign*$delta, 0)
         print line
EOF
	 
    #It overwrites the orginal trans.def file obtained in the dry run

    python generate_trans.py >> trans.def

    #It changes the   specified number of Coulomb integrals in the header of the .def file with the new one
    #It renames the s o-changed file trans.def to trans_new

    cat trans.def | sed 's/NTransfer.*/NTransfer     '$(($L*8))'/g' > trans_new
    mv trans_new trans.def

    #Back up in memory of the definitive trans.def file

    cp trans.def trans.def.bak

    echo "trans.def OK"
#------------------------------------------------------------------------------------------------
#Generate coulombinter.def ---> file with the F-F interaction
#------------------------------------------------------------------------------------------------

    cat > generate_coulombinter.py <<EOF
i=0
while i < $L:
    if 2*i + 2 == $L:
        line = "%5d %5d %25.15f" % (2*i, 0, $Vpp)
        print line
        break
    else:
        line = "%5d %5d %25.15f" % (2*i, 2*i+2, $Vpp)
        print line
    i = i+1 
EOF

    #same as trans.def file

    if [ "$Vpd" == "0" ]; then
	cp -f header_CI.def coulombinter.def
	python generate_coulombinter.py >> coulombinter.def
	cat coulombinter.def | sed 's/NCoulombInter.*/NCoulombInter     '$(($L*3/2-$L))'/g' > coulombinter_new
	mv coulombinter_new coulombinter.def
	cp coulombinter.def coulombinter.def.bak
    else
	python generate_coulombinter.py >> coulombinter.def
	cat coulombinter.def | sed 's/NCoulombInter.*/NCoulombInter     '$(($L*3/2))'/g' > coulombinter_new
	mv coulombinter_new coulombinter.def
	cp coulombinter.def coulombinter.def.bak
    fi
	
    
    echo "coulombinter.def OK"

    #Running of HPhi

    echo "Run of HPhi"
    HPhi -e namelist.def > output_exp_$delta
    echo "Done!"
    
    #Get the energy

    energy=`cat output/zvo_energy.dat | grep Energy | awk '{print $2}'`
    echo "$energy" >> "$destdir2"

done

-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by rp092** [comment]
![correlation functions issue 53 issp center dev hphi](https://user-images.githubusercontent.com/38993526/49436101-827be180-f7b8-11e8-8bcb-c1a28cbb6698.png)

Those are the problems

**Comment by k-yoshimi** [comment]
@rp092 
the script is too complex.
please upload all input files at Delta/t =-300.

**Comment by k-yoshimi** [comment]
@rp092 
I think that when \delta > 0 and |\delta| >> V_{pp},
E_g = L/2(-\delta/2* + V_{pp}) ->  E_g /L = (-\delta/2 + V_{pp})/2.

In your case (\delta=300, V_{pp}=100), E_g/L = (-300/2+100)/2=-25.
When we calculate the eigenvalues by HPhi, 
we obtain E_g = -250.0999500513310920, i.e. E_g/L ~ -25.
Thus, I think that your orange plot line is incorrect.

**Comment by rp092** [comment]
Thank you. I'm sorry I have bothered you due to that oversight. 

R.

**Comment by k-yoshimi** [comment]
@rp092 
Don't mind. If you have any questions, please ask again !

**Comment by rp092** [comment]
That was the problem i was talking about. The first figure represents the case Vpd=0.0001 while the second one represents the case Vpd=0. How is it possibile that the Enregy plot changes so abruptly?
I'm not expecting this behaviour since at Vpd=0 the transition point should be always at delta=-Vpp

![figure_2](https://user-images.githubusercontent.com/38993526/49455821-187b3080-f7e8-11e8-8e40-da16ac50d2f8.png)
![figure_2-2](https://user-images.githubusercontent.com/38993526/49455822-187b3080-f7e8-11e8-9637-a4a5ed545d1b.png)

**Comment by rp092** [comment]
This is what i'm expecting to see.

![figure_3](https://user-images.githubusercontent.com/38993526/49456265-15347480-f7e9-11e8-9fda-4083d663483f.png)

**Comment by k-yoshimi** [comment]
@rp092 
It looks some strange. 
When I calculated the ground state energy at (\delta, Vpd) = (-30, 0) by HPhi, 
I obtained the value Eg = 2.96915249334723e+01.
But you obtained Eg ~ -7.5e+01.

I uploaded the input files I used in my calculation below.
So please check the value by using these input files.
(I recommended you not to write input files directly in this issue but make zip file and upload it.)
[sample_delta30_Vpp0.zip](https://github.com/issp-center-dev/HPhi/files/2646222/sample_delta30_Vpp0.zip)

**Comment by rp092** [comment]
In file trans.def that you uploaded there are 65 rows so 60 transfer integrals (5 rows of header) but Ntransfer is 80. Shouldn't it be uncorrect?

R.

**Comment by k-yoshimi** [comment]
Sorry, you are right. Please replace 80 by 60.

**Comment by rp092** [comment]
I've already done it, but it gives me an error message.
Instead if I run HPhi with Ntransfer = 80 there are no problems.

[output-sdry.zip](https://github.com/issp-center-dev/HPhi/files/2648312/output-sdry.zip)

**Comment by k-yoshimi** [comment]
I think that the blank line exists at the last line in trans.def file and HPhi counts it.
So please delete the blank line.

**Comment by rp092** [comment]
ok with your input files I obtain your results Egs ~ 29.

I have a question: supposing that in my systems there are only up spins (s = 0 in Hphi language) why the dry run  creates also terms in the trans.def file with  s = 1, despite I saturated 2sz to nelec in the input file?

**Comment by k-yoshimi** [comment]
@rp092 
Because, 2Sz is the condition for the system and not related to the model.
By the way, I wonder why your result is not same compared to my result.
Can you upload the zip file including input files that you obtained Egs~ -75 by HPhi.

**Comment by k-yoshimi** [comment]
In your input file, I found that there are transfer operators that Sz is not conserved.
For example, in trans.def file that you uploaded, there are following components:
``` 
0     0     0     1       150.000000000000000         0.000000000000000
0     1     0     0       150.000000000000000         0.000000000000000
```
It might give a wrong result though I do not check it yet.
Please check it carefully.

**Comment by rp092** [comment]
That was the motivation of my question and i fixed it.
parameters L=10 nelec=5 Vpd=0 Vpp=100 delta=-30 (remember that my staggered potential is Δ/2 Σ_ j (-1)^j c*_ j c_ j so you will encounter terms with half the value you put in) 

[parameters.zip](https://github.com/issp-center-dev/HPhi/files/2648545/parameters.zip)

**Comment by k-yoshimi** [comment]
@rp092 
I found that your namelist lacks coulombinter file.

**Comment by k-yoshimi** [comment]
@rp092
When I added the coulombinter in namelist file,  Egs becomes 1.46382394059564e+01.

**Comment by rp092** [comment]
I noticed that when I put V = 0 in the .in file the resulting coulombinter.def file is empty so the resulting production of the next-nearest neighbor interaction on even sites results in a coulombinter.def file which hasn't the header. To avoid that I put in another file called "Header_CI.def" the first 5 rows (header) which I copy  in the coulombinter.def file. Here is the part of the entire script which deals with that job:

[coulomb.zip](https://github.com/issp-center-dev/HPhi/files/2648983/coulomb.zip)

So is it a problem for HPhi if some .def file doesn't have the proper header?

**Comment by rp092** [comment]
to be more precise if in the .in file V = 0 and then I add the next-nearest neighbor interaction the resulting coulombinter.def file is something like that

    0     2       100.000000000000000
    2     4       100.000000000000000
    4     6       100.000000000000000
    6     8       100.000000000000000
    8     0       100.000000000000000

without the header, which in that case it should be

__=============================================
NCoulombInter     5_
_=============================================
================== CoulombInter ================
=============================================__

 Does it represents a problem for HPhi?

**Comment by rp092** [comment]
![figure_4](https://user-images.githubusercontent.com/38993526/49518552-3192e880-f89f-11e8-938f-f9910fe9315f.png)

Here is the case with Vpd = Vpp = 0. Considering that is the same as the case with Vpp=100 It seems clear to me that HPhi doesn't see the coulombinter.def file

**Comment by k-yoshimi** [comment]
Sorry, I don't understand what you mean.

I think that when V=0 in std.in, HPhi does not add ``coulombinter`` in namelist.def:
```
         ModPara  modpara.def
         LocSpin  locspn.def
           Trans  trans.def
        OneBodyG  greenone.def
        TwoBodyG  greentwo.def
         CalcMod  calcmod.def
  PairExcitation  pair.def
     SpectrumVec  zvo_eigenvec_0
```
Thus, even if you make  ``coulombinter`` file, it is not read.


On the other hand, when V is not equal to 0 in std.in, HPhi adds ``coulombinter`` in namelist.def:
```
         ModPara  modpara.def
         LocSpin  locspn.def
           Trans  trans.def
    CoulombInter  coulombinter.def
        OneBodyG  greenone.def
        TwoBodyG  greentwo.def
         CalcMod  calcmod.def
  PairExcitation  pair.def
     SpectrumVec  zvo_eigenvec_0
```

In this case, `` coulombinter.def `` file is read.

**Comment by k-yoshimi** [comment]
Did you check ``namelist.def`` ?

**Comment by rp092** [comment]
So if V=0 but I want also to insert a next nearest neigbhor interaction in the system in which .def file do I have to write it? Not in coulombinter.def I suppose now.

**Comment by rp092** [comment]
> Did you check `namelist.def` ?

yes indeed for all Delta when V=0 the problem still remains. So now I understand a thing: if V = 0 coulombinter.def is not read.

**Comment by k-yoshimi** [comment]
When you want to add next nearest neigbhor interaction at V=0 from ``std.in`` ,
after running ``HPhi -sdry std.in``, you must add ``CoulombInter  coulombinter.def`` in ``namelist.def``.
Next, you make ``coulombinter.def`` file like this:
```
=============================================
NCoulombInter     5
=============================================
================== CoulombInter ================
=============================================
0     2       100.000000000000000
2     4       100.000000000000000
4     6       100.000000000000000
6     8       100.000000000000000
8     0       100.000000000000000
```
Then the calculation is correctly done.

**Comment by k-yoshimi** [comment]
OK, I see what happens before. 

The format of the files to define coulomb-inter interactions is
```
Line 1: Header
Line 2: [string01] [int01]
Lines 3-5: Header
Lines 6-: [int02] [int03] [double01].
```
as written in http://issp-center-dev.github.io/HPhi/manual/en/html/filespecification/expertmode_en/CoulombInter_file_en.html.

In HPhi, Line 1 and Line 3-5 are not read.
So when you made coulombinter.def file like this:
```
0     2       100.000000000000000
2     4       100.000000000000000
4     6       100.000000000000000
6     8       100.000000000000000
8     0       100.000000000000000
```
HPhi recognizes 2nd line
``2     4       100.000000000000000``
and set NCoulombInter as 4, because first word corresponding the word ``NCoulombInter`` (in this case ``2``) is skipped.
Though HPhi recognizes NCoulombInter = 4, this number is only used to store memory. 
Thus, HPhi can read 4 components but in this case any coulomb interactions are read because this file only has 5 lines (components are read from Line 6). This is why HPhi does not fail and the result does not depend on Vpp. 

Though we set HPhi to fail if the total number of components is larger than NCoulombInter,
it might be better also to set HPhi to fail if it is smaller than NCoulombInter as well.
