### ISSUE TITLE
Parallel Computing

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#57]
Hi Evreyone

My PC has 4 four CPU cores. How can I run HPhi only on one of them and letting the other three to do other tasks with HPhi?

Thanks a lot

Riccardo.

**Comment by k-yoshimi** [comment]
You can use 1 CPU core for HPhi by setting ``export OMP_NUM_THREADS=1`` in your terminal before running HPhi.

**Comment by rp092** [comment]
thanks a lot
