### ISSUE TITLE
スピン S=1 量子系での境界条件

### ISSUE THREAD

**Issue by knomura-kyushu-u** [issp-center-dev/HPhi#58]
スピン S=1 量子系で，ひねり境界条件を HPhi で扱おうとしています．
 ところがマニュアルに目を通した範囲では，
S=1/2 で電子系の形に焼き直して局所的に結合定数を変更する形(エキスパートモードでInterAll 指定ファイル)は載っていますが，
S=1 でのやり方が分かりません．

3種類のフェルミオンを使えばよいようですが，マニュアルでは電子系でスピンアップやダウンの2種類(S=1/2)
しか扱えないようによめます．

どのようにすれば良いかアドバイスをいただければ幸いです．

**Comment by k-yoshimi** [comment]
@knomura-kyushu-u 
スピンS=1ですが、LocSpin指定ファイルでスピンのindexを``2``とすると指定することが可能です。
http://issp-center-dev.github.io/HPhi/manual/ja/html/filespecification/expertmode_ja/LocSpin_file_ja.html

これを設定することで、スピンのindexが```0, 1, 2```で取れるようになり、
3種類のフェルミオンを扱えるようになります。
LocSpinで指定したスピンindexは、
相互作用を定義するInterAllなどのスピンindexにも適用されるので、
それに従い各種相互作用を定義できます。

以上の手順で計算ができると思います。
もし、設定がうまくいかない場合には、お気軽にご連絡ください。
よろしくお願いします。

**Comment by knomura-kyushu-u** [comment]
k-yoshimi さま，

ありがとうございます．試してみます．
