### ISSUE TITLE
current current correlation function

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#61]
Hi everyone,

As I saw in HPhi guide the computation of a dynamical Green function I(z) involves the specification of the operator O in the following formula

 I(z) = <Φ_0|O  (H-zI)^-1  O|Φ_0>

O could be either a single body or a two body operator. In the latter case the specifictation of O occurs through the modification of pair.def file. Suppose that O is equal to

j = -i Σ_l c*_l c_l+1 - c*_l+1 c_l             (l site index, no spin, chain lattice) 

so that I(z) is the current-current correlation function. Here is my doubt: if I run the computation of such correlation function specifiying only 

CalcSpec = "Normal"
OmegaIM = -0.1
NOmega = 5000

I read that SpectrumQW, SpectrumQL are set by default equal to 0 but the GF that I would like to compute is k-indipendent. So how can I compute such GF without obtaining a k-dipendent result?

thanks a lot
Riccardo

**Comment by rp092** [comment]
To be more precise:
Givent that the specification of SpectrumQW, SpectrumQL occurs by default, does the calculation of any Dynamical GF always gives a result in the k-space?

Riccardo

**Comment by k-yoshimi** [comment]
@rp092
In many cases of my calculations, I directly define the pair.def files and calculate the dynamical Green’s functions first by expert mode. After finishing the calculation, I recalculate physical quantities from the obtained numerical results by using some scripts.

**Comment by rp092** [comment]
What I would like to calculate is

J(ω) = -Im[G_R(ω)]

where G_R(ω) is the retarded green function defined so defined

<Φ_0| j*  [H-(E_gs +ω)]^-1  j |Φ_0>

where j = -i Σ_l c*_l c_l+1 - c*_l+1 c_l (l site index)
My system has no spin and has that 1D hamiltonian:

H = -t Σ_i c*_i c_i+1 + c*_i+1 c_i   +   Δ/2 Σ_i (-1)^i n_i   +  V Σ_i  n_i n_i+1

where n_i is the number operator. I'm checking my results with the ones from
the enclosed article but I obtain only the first spike at the correct frequency but not the others
[gagliano1988.pdf](https://github.com/issp-center-dev/HPhi/files/2869455/gagliano1988.pdf)

Here are my scripts. (They are not long)
[files_for_current_current_corr_func.zip](https://github.com/issp-center-dev/HPhi/files/2869423/files_for_current_current_corr_func.zip)

If you can give me any help I would appreciate that a lot.

Riccardo.

**Comment by rp092** [comment]
The error was on anti-periodic BC. 
Just antoher question:
With "imaginary part of c*c" you mean, for example that each of the terms in J = -i Σ_l c*_l c_l+1 - c*_l+1 c_l should have a +1 or a -1 in the relative column ?

R.

**Comment by k-yoshimi** [comment]
@rp092 
On anti-periodic BC, transfer integral must have the factor -1 for the bond across the boundary.
In your script, this factor is not considered. 
```
for l in range($L):
   m = l+1
   m = m % $L
   line1="%d %d %d %d %d %.1f %.1f" % (l,0,m,0,1,0.0,-1.0)
   line2="%d %d %d %d %d %.1f %.1f" % (m,0,l,0,1,0.0,1.0)
   print line1
   print line2
EOF
```
In this case, when ``m=L (=0)``,  the procedure should be modified as 
```
   line1="%d %d %d %d %d %.1f %.1f" % (l,0,m,0,1,0.0,1.0)
   line2="%d %d %d %d %d %.1f %.1f" % (m,0,l,0,1,0.0,-1.0)
```
I think that the error came from this.

> With '' imaginary part of c_dagger c '' you mean, for example that each of the terms in J = -i Σ_l c*_l c_l+1 - c*_l+1 c_l should have a +1 or a -1 in the relative column ?

Yes, you're right.

**Comment by rp092** [comment]
thanks a lot
