### ISSUE TITLE
2D lattice

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#63]
Hi Everyone, 
I would like to implement a 2D lattice like this [reticolo.pdf](https://github.com/issp-center-dev/HPhi/files/2957421/reticolo.pdf) in HPhi. The straight lines represent the first neighbor connection between the sites while the dashed ones mimic the periodic bonduary condition to implement. 
The Hamiltonian is the Heisenberg one with Jx=Jy=Jz=J. Can you advise me which is the file (in expert mode I suppose) to modify to reach that purpose?

Riccardo

**Comment by rp092** [comment]
Or, If you prefer, here is a Graph table of the lattice: [graph.zip](https://github.com/issp-center-dev/HPhi/files/2961982/graph.zip)

Riccardo

**Comment by k-yoshimi** [comment]
@rp092 
The simple way to construct the Heisenberg Hamiltonian is to define the Hamiltonian by using [Ising](http://issp-center-dev.github.io/HPhi/manual/en/html/filespecification/expertmode_en/Ising_file_en.html) and [Exchange](http://issp-center-dev.github.io/HPhi/manual/en/html/filespecification/expertmode_en/Exchange_file_en.html) files.
For example, the Hamiltonian for 6-site one-dimensional Heisenberg model is given by the following files;
- Ising file
```
======================
NIsing 6
======================
========Ising ======
======================
   0     1  0.50000
   1     2  0.50000
   2     3  0.50000
   3     4  0.50000
   4     5  0.50000
   5     0  0.50000
```

- Exchange file
```
======================
NExchange 6
======================
========Exchange ======
======================
   0     1  0.50000
   1     2  0.50000
   2     3  0.50000
   3     4  0.50000
   4     5  0.50000
   5     0  0.50000
```

**Comment by rp092** [comment]
To specify the shape of the simulation cell it is sufficient to set a0W, a0L, a1L and a1W right?

So my case correspond to
a0W=4
a0L=-4
a1W=4
a1L=4

Am I wrong?

R.

**Comment by mitsuaki1987** [comment]
@rp092 
```
a0W=3
a0L=2
a1W=3
a1L=-2
```
and try 
``` sh
$ gnuplot lattice.gp
```
after running `HPhi -sdry input`.

Best regards,
Mitsuaki Kawamura
ISSP

**Comment by k-yoshimi** [comment]
You can see the shape by typing ``gnuplot lattice.gp``  after running ``HPhi -sdry stan.in``.
For the above case, the shape of the simulation cell becomes as [Figure 0.pdf](https://github.com/issp-center-dev/HPhi/files/2983730/Figure.0.pdf).
I think that this lattice is different from what you want. Since the Hexagon type lattice is not defined in Standard mode, you should define the lattice directly by labeling the sites.

**Comment by rp092** [comment]
Thanks a lot.

R.

**Comment by rp092** [comment]
Hi everyone, 

once this lattice has been implemented, if I proceed within the Heisenberg model both with the calculation of the GS energy and with the calculation of the GS vector, the operation is partially successful: the program prints the value of the GS energy on screen but when it proceeds in the calculation of the GS vector it does not arrive at convergence. I tried to relax the "lanczoseps" condition up to insert very small values, like 4, or to consider a greater tolerance on the error committed in the determination of this vector, without reaching the objective.

Since this is a standard system that I am using as a benchmark for my future simulations on the Heisenberg model, could you advise me which other parameters to modify to get at least the GS vector?

**Comment by k-yoshimi** [comment]
@rp092 
CG method may work well for your calculation. Did you try it?

**Comment by rp092** [comment]
@k-yoshimi 
Yes I did: if _calceigenvec_ is set to 0  in _calcmode_ file the program proceeds with the Lanczos method and then with the CG one in case of failure of the former. Within this framework HPhi always aborts the job approximately after 90 iterations. Is it possible to tune the maximum number of iterations that the Lanczos method can perform?

**Comment by k-yoshimi** [comment]
@rp092 
I didn't mean to set ``calceigenvec  = 0``.
Please set ``CalcType  = 3`` in ``calcmode`` file.
In this mode, the eigen values and vectors are obtained at once by LOBCG method.
