### ISSUE TITLE
Spin operators

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#64]
hi every one,

by studying your user guide I realized that in the file pair.def one can specify the site and spin indexes of a generic two-body operator A. It is then possible to calculate the relative dynamic Green function by reconstruction of the quantity <ψ_0| A* (H-zI)^-1 A |ψ_0>. Furthermore in paragraph 4.2.17 it is written that the form of this operator must be given in terms of the fermionic operators c and c*. Since the columns that make up the file allow the specification of at most two spin indexes and two different site indexes, I would like to ask you the following question:

If I had as Hamiltonian the one from the Heisenberg model and if I had to calculate with HPhi  the spectral function of an operator composed by four different spin operators, such as:

Σ_ν <GS| B^x_q |ν> <ν| B^y_q |GS>  δ( ω + E_GS - E_ν)   

where B^x_q = (1/sqrt N) Σ_ j exp(i q * R_ j ) S_R_ j * S_R_ j + x
where B^y_q = (1/sqrt N) Σ_ m exp(i q * R_ m ) S_R_ m * S_R_ m + y

S = (Sx.Sy,Sz) 
asterisks in formulas mean scalar product
x and y refer to the x axis and y axis versors

how could I insert the indices for eight different fermion operators? 
I speak of eight indices because each spin operator is described by two fermion operators (see paragraph 3.2.3).

Thanks in advance for your reply and as always I am grateful for the help you are giving us.

Riccardo

**Comment by rp092** [comment]
Perhaps is there the possibility of compiling a specific file for spin excitations without considering their representation through the fermionic creation and destruction operators?

Riccardo

**Comment by k-yoshimi** [comment]
@rp092 
In ver. 3.1, HPhi cannot treat the eight indices operators. Thus, you must modify Hphi.
I think that the simple manner to generate excited state obtained by  the eight indices operators is to implement the  mode to output the excited state, i.e. you first output pair excited state and then multiply pair excited state again.

**Comment by rp092** [comment]
Therefore, for example we consider only one of the terms obtained from the scalar product of the spin operators : <GS| S^x_l S^x_l+x S^x_m S^x_m+y |GS>. What you meant is to first calculate the quantity S^x_m S^x_m+y |GS> with HPhi and then use it as a fictitious ground state (let's call it |GS*>) in order to compute S^x_l S^x_l+x |GS*> ?

Riccardo

**Comment by k-yoshimi** [comment]
@rp092 
Yes. But if you are used to modify hphi, it would be nice to implement the mode for multiplying 4 pairs exciting operators and do a pull request on this repository.

**Comment by rp092** [comment]
> I think that the simple manner to generate excited state obtained by the eight indices operators is to implement the mode to output the excited state, i.e. you first output pair excited state and then multiply pair excited state again.

Let ABCD |Gs> be the quantity I want to calculate with HPhi.
How can I set the program to get the excited state CD |Gs> in ouput? through a first calculation with HPhi I get the ground state vector |Gs> by explicitly writing "eigenvecIO = out" and "method = Lanczos" in the input file. Then?
I guess I have to run the simulation at least two more times to achieve the objective. right?

**Comment by rp092** [comment]
I accidentally clicked on the button "close issue"

**Comment by rp092** [comment]
> Therefore, for example we consider only one of the terms obtained from the scalar product of the spin operators : <GS| S^x_l S^x_l+x S^x_m S^x_m+y |GS>. What you meant is to first calculate the quantity S^x_m S^x_m+y |GS> with HPhi and then use it as a fictitious ground state (let's call it |GS*>) in order to compute S^x_l S^x_l+x |GS*> ?

My bad, I made a mistake while I was explaining my problem to you. In the aforementioned case the spectral function was  <GS| S^x_l S^x_l+x  (zI-H)^-1  S^x_m S^x_m+y |GS> or of the type <GS|AB (zI-H)^-1 CD|Gs> and not <GS|ABCD (zI-H)^-1 ABCD|Gs>

I apologize for the error.

Riccardo

**Comment by k-yoshimi** [comment]
@rp092 
> I guess I have to run the simulation at least two more times to achieve the objective. right?

Yes, right.

> HPhi I get the ground state vector |Gs> by explicitly writing "eigenvecIO = out" and "method = Lanczos" in the input file. Then?

First, you write the following codes after making excited vector in``CalcSpectrum.c``.

```
	//Output excited vector
	if (X->Bind.Def.iOutputExVec == 1) {
	  sprintf(sdt, cFileNameOutputExcitedVec, X->Bind.Def.CDataFileHead, myrank);
	  if(childfopenALL(sdt, "w", &fp)!=0){
		return -1;
	  }   
	fwrite(&X->Bind.Large.itr, sizeof(X->Bind.Large.itr),1,fp);
	fwrite(&X->Bind.Check.idim_max, sizeof(X->Bind.Check.idim_max),1,fp);
	fwrite(v1, sizeof(complex double),X->Bind.Check.idim_max+1, fp);
	fclose(fp);
	return TRUE;
	}

```

Next, compile HPhi again and change the mode to calculate under the spectrum mode but set "eigenvecIO = out" . In this case, HPhi finishes after outputting the excited vector. Then, delete "eigenvecIO = out", and calculate the spectrum. 

But as you mentioned before,  you need some efforts to calculate <ψ_0| B^* (H-zI)^-1 A |ψ_0>, since HPhi assumes B=A. To obtain these values, you first calculate Re <ψ_0| B^* (H-zI)^-1 A |ψ_0> by combining
1. <ψ_0| (A+B)^* (H-zI)^-1 (A+B) |ψ_0> 
2. <ψ_0| A^* (H-zI)^-1 A |ψ_0> 
3. <ψ_0| B^* (H-zI)^-1 B |ψ_0> 

and then obtain imaginary parts by using Kramers-Kronig relation.

**Comment by rp092** [comment]
> Next, compile HPhi again and change the mode to calculate under the spectrum mode but set "eigenvecIO = out" . 

does spectrum mode exist by chance? or you mean standard?

**Comment by rp092** [comment]
Do you mean after "//normalize vector" and before  "//Reset list_1, list_2_1, list_2_2" in file CalcSpectrum.c (line 219) or directly after "//calculate Diagonal term" (line 229)?

**Comment by k-yoshimi** [comment]
> Do you mean after "//normalize vector" and before "//Reset list_1, list_2_1, list_2_2" in file CalcSpectrum.c (line 219) or directly after "//calculate Diagonal term" (line 229)?

To output excited vector, you should insert the codes for the output procedure after "//normalize vector"  and before "//Reset list_1, list_2_1, list_2_2" in file.

**Comment by rp092** [comment]
once implemented the changes you suggested, I ran into this error:

_/home/nik-malanno/Scaricati/HPhi-3.1.2/src/CalcSpectrum.c: In function ‘CalcSpectrum’:
/home/nik-malanno/Scaricati/HPhi-3.1.2/src/CalcSpectrum.c:221:18: error: ‘struct DefineList’ has no member named ‘iOutputExVec’; did you mean ‘iOutputMode’?
  if (X->Bind.Def.iOutputExVec == 1) {
                  ^~~~~~~~~~~~
                  iOutputMode
/home/nik-malanno/Scaricati/HPhi-3.1.2/src/CalcSpectrum.c:222:17: error: ‘cFileNameOutputExcitedVec’ undeclared (first use in this function); did you mean ‘cFileNameOutputRestartVec’?
    sprintf(sdt, cFileNameOutputExcitedVec, X->Bind.Def.CDataFileHead, myrank);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                 cFileNameOutputRestartVec
/home/nik-malanno/Scaricati/HPhi-3.1.2/src/CalcSpectrum.c:222:17: note: each undeclared identifier is reported only once for each function it appears in
src/CMakeFiles/HPhi.dir/build.make:806: recipe for target 'src/CMakeFiles/HPhi.dir/CalcSpectrum.c.o' failed
make[2]: *** [src/CMakeFiles/HPhi.dir/CalcSpectrum.c.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'src/CMakeFiles/HPhi.dir/all' failed
make[1]: *** [src/CMakeFiles/HPhi.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2_

Do you have any developers guide to orientate oneself in the code?

**Comment by k-yoshimi** [comment]
@rp092
Definelist is defined in include/struct.h.

**Comment by rp092** [comment]
Maybe I found a smarter way to calculate a green function like that

G = <ψ_0| H_ex (H_heisenberg-zI)^-1 H_ex |ψ_0>

where H_ex is equal to S1S2 and S1 and S2 are two different spin operators (so a 4 body operator in the fermionic language). I thought that given H = H_heisenberg I can first find its ground state, which I indicate with the notation |ψ^0_L> (L means "Lanczos")  and then I could apply the operator H_ex precisely on this state trough the following trick: just start a second HPhi run with |ψ^0_L>  as input vector and with H = H_ex; now the Lanczos algorithm must be blocked after a single step i.e. after the computation of H_ex |ψ^0_L>. Then get this state in output and then start a new Lanczos computation for the Dynamical GF with H_ex |ψ^0_L> as input vector and H as H_heisenberg again.

Now that's the question: looking at your code I noticed that in the _Lanczos_eigenvalue.c_ file there is the following part on line 104:

```
//Eigenvalues by Lanczos method
      TimeKeeper(X, cFileNameTimeKeep, cLanczos_EigenValueStart, "a");
      StartTimer(4101);
      mltply(X, v0, v1);
      StopTimer(4101);
      stp = 1;
      TimeKeeperWithStep(X, cFileNameTimeKeep, cLanczos_EigenValueStep, "a", stp);     
```
I believe that the function mltply does the operation | v0> = H_ex | v1> but its definition is in the Gran Canonical case. Could you by chance tell me where is the function that is right for my objective and maybe advise me on a possible modification of the code?

R.

**Comment by rp092** [comment]
Maybe I found a smarter way to calculate a green function like that

G = <ψ_0| H_ex (H_heis-zI)^-1 H_ex |ψ_0>

In this notationr H_heisenberg is composed by three parts (H_x + H_y + H_z, wher H_x and H_y contain the spin-flip terms and H_z the Sz Sz terms) and H_ex is equal to H_x - H_y (so a 4 body operator in the fermionic language). 

I thought that if I set H = H_heisenberg first I can find its ground state, which I indicate with the notation |ψ^0_L> (L means "Lanczos")  and then I could apply the operator H_ex precisely on this state trough the following trick: just start a second HPhi run with |ψ^0_L>  as input vector and with H = H_ex; now the Lanczos algorithm must be blocked after a single step i.e. after the computation of H_ex |ψ^0_L>. Then get this state in output and then start a new Lanczos computation for the Dynamical GF with H_ex |ψ^0_L> as input vector and H as H_heisagain.

Now that's the question: looking at your code I noticed that in the _Lanczos_eigenvalue.c_ file there is the following part on line 104:

```
//Eigenvalues by Lanczos method
      TimeKeeper(X, cFileNameTimeKeep, cLanczos_EigenValueStart, "a");
      StartTimer(4101);
      mltply(X, v0, v1);
      StopTimer(4101);
      stp = 1;
      TimeKeeperWithStep(X, cFileNameTimeKeep, cLanczos_EigenValueStep, "a", stp);     
```
I believe that the function mltply does the operation | v0> = H_ex | v1> but its definition is in the Gran Canonical case. Could you by chance tell me where is the function that is right for my objective and maybe advise me on a possible modification of the code?

R.

**Comment by rp092** [comment]
Maybe I found a smarter way to calculate a green function like that

G = <ψ_0| H_ex (H_heis-zI)^-1 H_ex |ψ_0>

where "heis" stands for "heisenberg". In this notation H_heis is composed by three parts (H_x + H_y + H_z, where H_x and H_y contain the spin-flip terms and H_z the Sz Sz terms) and H_ex is equal to H_x - H_y + H_z (so a 4 body operator in the fermionic language). 

I thought that if I set H = H_heisenberg first I can find its ground state, which I indicate with the notation |ψ^0_L> (L means "Lanczos")  and then I could apply the operator H_ex precisely on this state trough the following trick: just start a second HPhi run with |ψ^0_L>  as input vector and with H = H_ex; now the Lanczos algorithm must be blocked after a single step i.e. after the computation of H_ex |ψ^0_L>. Then get this state in output and then start a new Lanczos computation for the Dynamical GF with H_ex |ψ^0_L> as input vector and H as H_heis again.

Now that's the question: looking at your code I noticed that in the _Lanczos_eigenvalue.c_ file there is the following part on line 104:

```
//Eigenvalues by Lanczos method
      TimeKeeper(X, cFileNameTimeKeep, cLanczos_EigenValueStart, "a");
      StartTimer(4101);
      mltply(X, v0, v1);
      StopTimer(4101);
      stp = 1;
      TimeKeeperWithStep(X, cFileNameTimeKeep, cLanczos_EigenValueStep, "a", stp);     
```
I believe that the function mltply does the operation | v0> = H_ex | v1> but its definition is in the Gran Canonical case. Could you by chance tell me where is the function that is right for my objective and maybe advise me on a possible modification of the code?

R.

**Comment by rp092** [comment]
I look at your developer's guide 
http://issp-center-dev.github.io/HPhi/doxygen/_power_lanczos_8c.html#a72ac70ac22cd0e642dbf01a49683da87

On line 46 of _PowerLanczos.c_ the function mltply gets as input X v0 and v1. I think that in X it is written what kind of matrix-vector product I'm asking HPhi to do (In the sense that trough it the program recognizes what is the hamiltonian and chooses to compute mtlpyspinhalf() and so on) so I want to insert on line 47 a script that saves the result of the product H * v0 = v1 in a file like zvo_eigenvec_0_rank_0.dat and that then interrupts the execution of the program. Which is the right modification to do?

R.

**Comment by rp092** [comment]
I noticed that PowerLanczos.c it is not used when you compile HPhi. So I put that script in _LanczosEigenvalue.c_

 ```
//-------------------------------------------------------------------
     // Part added by Riccardo Piombo on 29/4/19 
     // to obtain Hex|psi_0_heis> flag_Hex must be set equal to 1
     flag_Hex=0;
     if(flag_Hex==1){
         childfopenALL("HR_psi0.dat","wb", &fp);
	 fwrite(v0, sizeof(complex double), X->Check.idim_max+1, fp);
	 fclose(fp);
	 fprintf(stdoutMPI,"HR_psi0 computed \n");	
	 exit(EXIT_SUCCESS);
	 }
     //------------------------------------------------------------------- 
```
It seems to work

R.

**Comment by k-yoshimi** [comment]
@rp092 
As you mentioned before, I also think that your modification works well in Grand canonical calculation.
