### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#68]
Hi, I have one question:
When I simulate the "spin" model specifying only the exchange constant J, the -sdry mode generates in particular four input files:
- exchange.def which contains the value of J
- Hund.def which contains the value of J_z (which in this case is equal to J since there is no anisotropy in the system)
- Trans.def (which is empty - so why does HPhi generate it?)
- Coulombinter.def
Here I do not understand why the latter is also generated. According to HPhi's guide, the V_ij values of the term sum_ij V_ij n_i n_j are written in it. What does this file have to do with the Heisenberg model?

I'm using your latest realease 3.2.0

Thanks as always for your help.
R.

**Comment by k-yoshimi** [comment]
@rp092 
The part of the hamiltonian SzSz can be rewritten by the Hund and  Coulombinter terms (though I think that it is smarter to use Ising term). See the following pdf.
[名称未設定.pdf](https://github.com/issp-center-dev/HPhi/files/3150550/default.pdf)

**Comment by rp092** [comment]
@k-yoshimi thanks for your reply.

Doubt n°2:
In case of computation of the dynamical Green function HPhi takes as input by defualt zvo_eigenvec0_rank0.dat. Dose exist the equivalent of this mechanism but in the case of Lanczos algorithm and not for the calculation of the spectrum? In other words: given the vector |x0> (for example the GS of a system obtained in another simulation) , how can I give the latter as the inital vector for the Lanczos Algorithm?

in practice:
1) Computation of the GS |psi0> of the heisenberg hamiltonian on a 2x2 square lattice
2) How to put |psi0> for a second Lanczos simulation which last only one step with another hamiltonian H'? (I need it to obtain H'|psi0>)
3) How to put  H'|psi0> as the input vector for the computation of the spectrum ( <psi_0| H' * (zI-H)^-1 H' |psi0>? just renaming the file that I save in the previous step as zvo_eigenvec0_rank0.dat?

**Comment by k-yoshimi** [comment]
@rp092 
Please specify the initial vector by the keyword ``SpectrumVec`` in the ``Calcmod`` file.
http://issp-center-dev.github.io/HPhi/manual/en/html/filespecification/expertmode_en/SpectrumVec_File_en.html

**Comment by rp092** [comment]
This should work in the last of the three step mentioned above. But in the first two I don't want to start the calculation of the spectrum. Does it work also in the computation of the lanczos basis?

R.

**Comment by k-yoshimi** [comment]
@rp092 
I think that the computation can be done by using ``Restart`` mode if the calculation be done in grand canonical system.

**Comment by rp092** [comment]
Only in case of GC? Why not simply Canonical?

**Comment by k-yoshimi** [comment]
@rp092 
If the Hamiltonian satisfies the conserved condition,  I think that the calculation can be done in the canonical mode.
But if not, the Hilbert space changes and thus, the calculation fails.

**Comment by rp092** [comment]
@k-yoshimi 
Got it. As weel as in the spectrum calculation, _spectrumvec_ must be specified in _calcmod.def_ where  do I have to specify the name of the vector file in input during the restart mode?

**Comment by k-yoshimi** [comment]
For restart mode,  the file name is fixed as ``tmp``.
For example, change ``zvo_eigenvec0_rank0.dat`` to ``zvo_tmp_rank0.dat``.
http://issp-center-dev.github.io/HPhi/manual/en/html/filespecification/outputfiles_en/tmpvec_en.html

**Comment by rp092** [comment]
@k-yoshimi 
So, in principle, it is possible to tell the program "do a Lanczos with one step only" or _number_of_interations_ = 1. In this case can _number_of_interations_ be specified via input or should I change the code?

**Comment by rp092** [comment]
I miss just one step (the bold one):
1) HPhi Lanczos with H = heisenberg
   - I get the GS with eigenvecIO=out
2) HPhi Lanczos with H = H' different from Heisenberg
   - **put GS of heisenberg as input**
   - Lanczos_max 1
   - Restart = restart_in + restart_out
3) calculation of <psi_0| H' * (zI-H)^-1 H' |psi0>
   - modify spectrumvec in calcmod.def

**Comment by rp092** [comment]
why if I perform in restart mode the calcultaion of the GS Energy eigenvalue HPHI says that the algoritmh has not reached convergence while if I perform the same task but setting eigenvecIO=out it is succesful?

**Comment by rp092** [comment]
Dear @k-yoshimi 
I believe that I am wasting your time if I do not better explain the goal of the job I am doing which will be used to write a scientific paper: 

the computation of certain Green functions of the type <psi_0| H' * (zI-H)^-1 H' |psi0> where H' is  proportional to the scalar product of two spin operators and H is the Heisenberg Hamiltonian. Due to the fact that HPhi doesn't take into account any four-body fermionic operators that would result from the scalar product mentioned before I came up with a different way to do my job:
I didn't write H' at random, in fact the operator H' that appear before the ground state in the braket is similar to a Hamiltonian which is already implemented in HPhi, therefore I imagined the following algorithm:

1) using the Lanczos method I would like to obtain the ground state |psi0> of H
2) then I would like to change the input Hamiltonian from H to H' and to give |psi0> as input vector and at the same time I would like to use the Lanczos algorithm for only one step to get H' |psi0>
3) finally I would like to give H' | psi0> as the input vector for the final calculation of the spectrum
   <psi_0| H' * (zI-H)^-1 H' |psi0>.

I hope everything is clearer now.
Thanks for your help.

**Comment by k-yoshimi** [comment]
@rp092 
I saw the detail of the code in ``calcspectrum.c`` again and found that, for your calculation, some modifications will be needed (For example, add the function of inputting the excited vector and calculate spectrum). So, it's not simple to do your calculation by HPhi now and seems to need some times to do these modifications. If you'd like to add these functions by you. Please contact me directly (the e-mail is written in the following URL: http://pcoms.issp.u-tokyo.ac.jp/cultivation/youngresearchersyoshimiteam ) .  Because this issue is too detail to discuss here.

**Comment by rp092** [comment]
Ok I'll write you soon.

**Comment by rp092** [comment]
Let me know if you have received my email
