### ISSUE TITLE
biquadratic term

### ISSUE THREAD

**Issue by ultimatile** [issp-center-dev/HPhi#69]
Hello, I would like to diagonalize the S=1 bilinear biquadratic model.
Do you have a plan to implement for the biquadratic term (S_i \cdot S_j)^2?

**Comment by mitsuaki1987** [comment]
It seems no developers have such plan.

**Comment by yyamaji** [comment]
Motivation exists. The resource is not enough.
@ultimatile
Are you interested in the implementation?

**Comment by ultimatile** [comment]
Yes, but in this case, I will implement to my cloned HΦ code by trial and error because I am a beginner of C.

**Comment by ultimatile** [comment]
I understood that the biquadratic term is expressed as the interall. Thank you.
