### ISSUE TITLE
Question regarding parameters. 

### ISSUE THREAD

**Issue by georgeyumnam** [issp-center-dev/HPhi#84]
Hi,
I would like to know if there is a height parameter that can be provided. In the case of length and width, there exists the following: Llength, and Wlength. Is there a similar parameter for height?

I am also wondering if there is a way to compute the J'/J parameters (rather than using them as inputs), for a certain set of lattice geometry within the Heisenberg model? 

Thank you very much.

**Comment by tmisawa** [comment]
@georgeyumnam 
Hi.

For the first question,
height parameter is specified by the keyword "Height".
For more details, please see the manual (around page 125). 

http://issp-center-dev.github.io/HPhi/manual/master/userguide_HPhi_en.pdf

For the second question,
what quantities do you want to  calculate J'/J from ?
J' and J can be separately specified in standard mode.
So, I think it is straightforward to calculate its ratio J'/J
from the input files.

**Comment by georgeyumnam** [comment]
Thank you for your reply. 
I have seen this parameter "Height" before, but I think this takes integer values and acts like a supercell dimensions like L, W. But I am looking for a parameter like Llength, Wlength in the case of the height. 

Regarding the second question, I am looking for a way to obtain the J2,J1 parameters as a result of an eigen value problem by giving the height parameter. Something similar to this MC simulation (G. Möller and R. Moessner, Phys. Rev. Lett. 96, 237202 (2006)). I am thinking of a simpler case, and I don't need to define the dipolar interaction, as I am only interested in the J1-J2 model. My goal is to obtain a similar plot like Fig.1b, but my plot would be a 2d plot: J2/J1 vs height. 

Thank you very much.

**Comment by tmisawa** [comment]
In  the case of the height, you can use Hlength.

For the second question, I would like to remind you that
Hphi only solves the eigenvalue problems for the given Hamiltonians.
So, please specify the Hamiltonian or the matrix that you want to consider.
In other words, please specify "an eigen value problem by giving the height parameter".

**Comment by georgeyumnam** [comment]
Thank you once again for your reply.
