### ISSUE TITLE
<SxSx> correlation function

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#86]
Isotropic (Jx=Jy=Jz=1) antiferromagnetic Heisenberg model 
2 x 2 square lattice

To compute the dynamical GF SxSx at q=(π,π) is the following input (pair.def) correct?

NPair 8

0 0 0 1 1         0.250000000000000         0.000000000000000
1 0 1 1 1        -0.250000000000000         0.000000000000000
2 0 2 1 1        -0.250000000000000         0.000000000000000
3 0 3 1 1         0.250000000000000         0.000000000000000
0 1 0 0 1         0.250000000000000         0.000000000000000
1 1 1 0 1        -0.250000000000000         0.000000000000000
2 1 2 0 1        -0.250000000000000         0.000000000000000
3 1 3 0 1         0.250000000000000         0.000000000000000

Edit 1: 0.25 is the factor in front of the GF given by the transformation fo Sx in terms of S+ and S-

Edit 2: I opened this issue because I expect this structure factor to be the same as the SzSz one since this system is isotropic. The latter is centered around 2J (1st Fig. attached) while the first one around J (2nd Fig. attached).
 I trust the first result since it is in agreement with what is written in the following article https://journals.aps.org/prb/abstract/10.1103/PhysRevB.40.239

![SpinSF_N_4](https://user-images.githubusercontent.com/38993526/66128845-fe200800-e5ee-11e9-9f9e-4d50da7c4329.png)

![SxSx](https://user-images.githubusercontent.com/38993526/66129083-830b2180-e5ef-11e9-8534-d1a30c710d06.png)

Thanks in advance for your cooperation

**Comment by k-yoshimi** [comment]
@rp092 
I calculated <SzSz> and <SxSx> at q=(π,π) on 2\times2 Heisenberg model and found that both results are same. I attached the sample tar file.
[Normal.tar.gz](https://github.com/issp-center-dev/HPhi/files/3686502/Normal.tar.gz)

You first obtain <SzSz> correlation function.
```
HPhi -s stan1.in
HPhi -s stan2.in
```
After that, you can obtain <SxSx> correlation function.
```
HPhi -e namelist_sx.def
``` 
As seen from pair_sx.def, the excited state is same that you wrote (though the factor is different).

Please check that your ground state of <SxSx> is same that of <SzSz> .

Best regards.

**Comment by rp092** [comment]
I don't know why but the risult is still wrong. 
I put my input files in a zip file so you can check that we are doing exactly the same things:

[SxSx.zip](https://github.com/issp-center-dev/HPhi/files/3686838/SxSx.zip)
heis2x2.in ----> your stan1.in
Spin_SF_xx.in ----> your stan2.in
pair_xx is a file to check pair.def generated by the dry run of the second .in file
shift_gf.py plot the GF

P.S: why don't you directly compute S+S- because the structure factor with SxSx corresponds to the imaginary part of <S+S- > but the latter provides two terms that are each other's hermit's conjugate ;therefore only one is needed: the one that is already implemented in HPhi, so <S+S->

**Comment by k-yoshimi** [comment]
I changed ``SpectrumType`` from ``S+S-`` to ``SzSz`` in your file ``Spin_SF_xx.in`` and  found that the peak of  <SzSz> is the same for that of  <SxSx> (purple line is the result of <SxSx> and that of <S+S->). I wonder why you set J = 0.5 in ``heis2x2.in``. In the report https://journals.aps.org/prb/abstract/10.1103/PhysRevB.40.239, J = 1.   
<img width="811" alt="スクリーンショット 2019-10-04 6 54 42" src="https://user-images.githubusercontent.com/4516893/66167009-e048b680-e673-11e9-9f3b-b88b29b4a8ce.png">

Please tell me that you also will obtain the same results by using the following attached tar file (I only added SpinSF_zz_2x2.in).
[SxSx_and_SzSz.tar.gz](https://github.com/issp-center-dev/HPhi/files/3688246/SxSx_and_SzSz.tar.gz)
If you will not obtain the same results, please tell me the version of HPhi.

> P.S: why don't you directly compute S+S-? the structure factor with SxSx corresponds to the imaginary part of <S+S- > but the latter provides two terms that are each other's hermit's conjugate ;therefore only one is needed: the one that is already implemented in HPhi, so <S+S->

Only I forgot that HPhi already implements the <S + S-> calculation function.

**Comment by rp092** [comment]
> I wonder why you set J = 0.5 in heis2x2.in. In the report https://journals.aps.org/prb/abstract/10.1103/PhysRevB.40.239, J = 1.

Because in HPhi there is a factor of two missing somewhere in the exchange constant:
- If you put J=0.5 you get the right GS energy which is analytic in the 2x2 square lattice case and equal to -2. Since form literature E_gs = -2J it seems as if J_real = 2J_input and J_input is the one in heis_2x2.in.


> Please tell me that you also will obtain the same results by using the following attached tar file (I only added SpinSF_zz_2x2.in).
SxSx_and_SzSz.tar.gz

If I use your input file I obtain your results and the two are equal, but  this time the peak is located at ω = 1 (once you shift ω by E_gs). However in
https://journals.aps.org/prb/abstract/10.1103/PhysRevB.40.239,
the SzSz structure factor gives a peak at ω = 2 and I obtain that result if I do not use the input file generated by the software in dry run but this one:
[pair_zz_2x2.zip](https://github.com/issp-center-dev/HPhi/files/3689983/pair_zz_2x2.zip)
which is different by a sign in the first for rows. 
To justify the arrangement of those signs, I am also enclosing the calcultaion  I made by hand
[computation_of_pair2x2def.pdf](https://github.com/issp-center-dev/HPhi/files/3689993/computation_of_pair2x2def.pdf)

**Comment by yomichi** [comment]
The standard mode of HPhi generates lattices with periodic boundary condition, so when length is 2, coupling constant is double counted.
In the present case, J=1 2x2 periodic square lattice becomes J=2 2x2 open square, in other words, 4 site ring.
This is why a factor of 2 seems missing to you.

I examined that k=(pi,pi) spectrum of 2x2 open square (this is nothing but k=pi spectrum of 4 site ring) is located at ω/J = 1.
I think the spectrum in the PRB paper is that of J=1 periodic 2x2 square, i.e., J=2 4 site ring.
Your attached operator file looks Sz(k=(0,pi)) if the lattice structure is unchanged.

Please check whether you have calculated SzSz and SxSx spectrum in the first case  for the same or the different model (energy scale).

**Comment by yomichi** [comment]
I think this is solved. If not, please re-open and comment.
