### ISSUE TITLE
GPU functionality

### ISSUE THREAD

**Issue by manicely6005** [issp-center-dev/HPhi#87]
I see that HPhi has MAGMA integration for GPU-acceleration. Can someone tell me to what extent HPhi utilizes the GPU. 

According to the documentation (below), there is multi-GPU support to solve full diagonalization. But the functionality can't be distributed using MPI across multi-CPU nodes?

> NGPU
Type : Int (default value: 2)
Description : (Full Diag)Select the number of GPU devices for full diagonalization:
ℋΦ does not support to use GPU devices at multi-nodes.

@jtetrea

**Comment by yomichi** [comment]
Yes, you are correct.
The GPU acceleration of HPhi replaces the diag API of LAPACK with that of MAGMA.
If your machine (one node or host) has two or more GPU boards, you can use the these GPUs simultaneously in single CPU process.

For details, the following benchmark report (p.6 of the PDF file) may help you:
http://www.issp.u-tokyo.ac.jp/supercom/activity-reports/2017/2017_0306_softwareadvancement
